<?php

namespace DoctrineProxies\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Base extends \Base implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Base' . "\0" . 'id', '' . "\0" . 'Base' . "\0" . 'name', '' . "\0" . 'Base' . "\0" . 'internalId', '' . "\0" . 'Base' . "\0" . 'format', '' . "\0" . 'Base' . "\0" . 'delimiter', '' . "\0" . 'Base' . "\0" . 'isTest', '' . "\0" . 'Base' . "\0" . 'originalText', '' . "\0" . 'Base' . "\0" . 'seller'];
        }

        return ['__isInitialized__', '' . "\0" . 'Base' . "\0" . 'id', '' . "\0" . 'Base' . "\0" . 'name', '' . "\0" . 'Base' . "\0" . 'internalId', '' . "\0" . 'Base' . "\0" . 'format', '' . "\0" . 'Base' . "\0" . 'delimiter', '' . "\0" . 'Base' . "\0" . 'isTest', '' . "\0" . 'Base' . "\0" . 'originalText', '' . "\0" . 'Base' . "\0" . 'seller'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Base $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setInternalId($internalId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInternalId', [$internalId]);

        return parent::setInternalId($internalId);
    }

    /**
     * {@inheritDoc}
     */
    public function getInternalId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInternalId', []);

        return parent::getInternalId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormat($format)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormat', [$format]);

        return parent::setFormat($format);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormat', []);

        return parent::getFormat();
    }

    /**
     * {@inheritDoc}
     */
    public function setDelimiter($delimiter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDelimiter', [$delimiter]);

        return parent::setDelimiter($delimiter);
    }

    /**
     * {@inheritDoc}
     */
    public function getDelimiter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDelimiter', []);

        return parent::getDelimiter();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsTest($isTest = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsTest', [$isTest]);

        return parent::setIsTest($isTest);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsTest()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsTest', []);

        return parent::getIsTest();
    }

    /**
     * {@inheritDoc}
     */
    public function setOriginalText($originalText = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOriginalText', [$originalText]);

        return parent::setOriginalText($originalText);
    }

    /**
     * {@inheritDoc}
     */
    public function getOriginalText()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOriginalText', []);

        return parent::getOriginalText();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeller(\Users $seller = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeller', [$seller]);

        return parent::setSeller($seller);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeller()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeller', []);

        return parent::getSeller();
    }

}
