insert into cities (name) values ('Abejorral-Antioquia');
insert into cities (name) values ('Abriaquí­-Antioquia');
insert into cities (name) values ('Acací­as-Meta');
insert into cities (name) values ('Acandí­-Chocó');
insert into cities (name) values ('Acevedo-Huila');
insert into cities (name) values ('Achí­-Bolí­var');
insert into cities (name) values ('Agrado-Huila');
insert into cities (name) values ('Agua de Dios-Cundinamarca');
insert into cities (name) values ('Aguachica-Cesar');
insert into cities (name) values ('Aguada-Santander');
insert into cities (name) values ('Aguadas-Caldas');
insert into cities (name) values ('Aguazul-Casanare');
insert into cities (name) values ('Agustí­n Codazzi-Cesar');
insert into cities (name) values ('Aipe-Huila');
insert into cities (name) values ('Albania-Caquetá');
insert into cities (name) values ('Albania-La Guajira');
insert into cities (name) values ('Albania-Santander');
insert into cities (name) values ('Albán-Cundinamarca');
insert into cities (name) values ('Albán (San José)-Nariño');
insert into cities (name) values ('Alcalá-Valle del Cauca');
insert into cities (name) values ('Aldana-Nariño');
insert into cities (name) values ('Alejandria-Antioquia');
insert into cities (name) values ('Algarrobo-Magdalena');
insert into cities (name) values ('Algeciras-Huila');
insert into cities (name) values ('Almaguer-Cauca');
insert into cities (name) values ('Almeida-Boyacá');
insert into cities (name) values ('Alpujarra-Tolima');
insert into cities (name) values ('Altamira-Huila');
insert into cities (name) values ('Alto Baudó (Pie de Pato)-Chocó');
insert into cities (name) values ('Altos del Rosario-Bolí­var');
insert into cities (name) values ('Alvarado-Tolima');
insert into cities (name) values ('Amagá-Antioquia');
insert into cities (name) values ('Amalfi-Antioquia');
insert into cities (name) values ('Ambalema-Tolima');
insert into cities (name) values ('Anapoima-Cundinamarca');
insert into cities (name) values ('Ancuya-Nariño');
insert into cities (name) values ('Andalucí­a-Valle del Cauca');
insert into cities (name) values ('Andes-Antioquia');
insert into cities (name) values ('Angelópolis-Antioquia');
insert into cities (name) values ('Angostura-Antioquia');
insert into cities (name) values ('Anolaima-Cundinamarca');
insert into cities (name) values ('Anorí­-Antioquia');
insert into cities (name) values ('Anserma-Caldas');
insert into cities (name) values ('Ansermanuevo-Valle del Cauca');
insert into cities (name) values ('Anzoátegui-Tolima');
insert into cities (name) values ('Anzá-Antioquia');
insert into cities (name) values ('Apartadó-Antioquia');
insert into cities (name) values ('Apulo-Cundinamarca');
insert into cities (name) values ('Apí­a-Risaralda');
insert into cities (name) values ('Aquitania-Boyacá');
insert into cities (name) values ('Aracataca-Magdalena');
insert into cities (name) values ('Aranzazu-Caldas');
insert into cities (name) values ('Aratoca-Santander');
insert into cities (name) values ('Arauca-Arauca');
insert into cities (name) values ('Arauquita-Arauca');
insert into cities (name) values ('Arbeláez-Cundinamarca');
insert into cities (name) values ('Arboleda (Berruecos)-Nariño');
insert into cities (name) values ('Arboledas-Norte de Santander');
insert into cities (name) values ('Arboletes-Antioquia');
insert into cities (name) values ('Arcabuco-Boyacá');
insert into cities (name) values ('Arenal-Bolí­var');
insert into cities (name) values ('Argelia-Antioquia');
insert into cities (name) values ('Argelia-Cauca');
insert into cities (name) values ('Argelia-Valle del Cauca');
insert into cities (name) values ('Ariguaní­ (El Difí­cil)-Magdalena');
insert into cities (name) values ('Arjona-Bolí­var');
insert into cities (name) values ('Armenia-Antioquia');
insert into cities (name) values ('Armenia-Quindí­o');
insert into cities (name) values ('Armero (Guayabal)-Tolima');
insert into cities (name) values ('Arroyohondo-Bolí­var');
insert into cities (name) values ('Astrea-Cesar');
insert into cities (name) values ('Ataco-Tolima');
insert into cities (name) values ('Atrato (Yuto)-Chocó');
insert into cities (name) values ('Ayapel-Córdoba');
insert into cities (name) values ('Bagadó-Chocó');
insert into cities (name) values ('Bahí­a Solano (Míºtis)-Chocó');
insert into cities (name) values ('Bajo Baudó (Pizarro)-Chocó');
insert into cities (name) values ('Balboa-Cauca');
insert into cities (name) values ('Balboa-Risaralda');
insert into cities (name) values ('Baranoa-Atlántico');
insert into cities (name) values ('Baraya-Huila');
insert into cities (name) values ('Barbacoas-Nariño');
insert into cities (name) values ('Barbosa-Antioquia');
insert into cities (name) values ('Barbosa-Santander');
insert into cities (name) values ('Barichara-Santander');
insert into cities (name) values ('Barranca de Upí­a-Meta');
insert into cities (name) values ('Barrancabermeja-Santander');
insert into cities (name) values ('Barrancas-La Guajira');
insert into cities (name) values ('Barranco de Loba-Bolí­var');
insert into cities (name) values ('Barranquilla-Atlántico');
insert into cities (name) values ('Becerrí­l-Cesar');
insert into cities (name) values ('Belalcázar-Caldas');
insert into cities (name) values ('Bello-Antioquia');
insert into cities (name) values ('Belmira-Antioquia');
insert into cities (name) values ('Beltrán-Cundinamarca');
insert into cities (name) values ('Belén-Boyacá');
insert into cities (name) values ('Belén-Nariño');
insert into cities (name) values ('Belén de Bajirá-Chocó');
insert into cities (name) values ('Belén de Umbrí­a-Risaralda');
insert into cities (name) values ('Belén de los Andaquí­es-Caquetá');
insert into cities (name) values ('Berbeo-Boyacá');
insert into cities (name) values ('Betania-Antioquia');
insert into cities (name) values ('Beteitiva-Boyacá');
insert into cities (name) values ('Betulia-Antioquia');
insert into cities (name) values ('Betulia-Santander');
insert into cities (name) values ('Bituima-Cundinamarca');
insert into cities (name) values ('Boavita-Boyacá');
insert into cities (name) values ('Bochalema-Norte de Santander');
insert into cities (name) values ('Bogotá D.C.-Cundinamarca');
insert into cities (name) values ('Bojacá-Cundinamarca');
insert into cities (name) values ('Bojayá (Bellavista)-Chocó');
insert into cities (name) values ('Bolí­var-Antioquia');
insert into cities (name) values ('Bolí­var-Cauca');
insert into cities (name) values ('Bolí­var-Santander');
insert into cities (name) values ('Bolí­var-Valle del Cauca');
insert into cities (name) values ('Bosconia-Cesar');
insert into cities (name) values ('Boyacá-Boyacá');
insert into cities (name) values ('Briceño-Antioquia');
insert into cities (name) values ('Briceño-Boyacá');
insert into cities (name) values ('Bucaramanga-Santander');
insert into cities (name) values ('Bucarasica-Norte de Santander');
insert into cities (name) values ('Buenaventura-Valle del Cauca');
insert into cities (name) values ('Buenavista-Boyacá');
insert into cities (name) values ('Buenavista-Córdoba');
insert into cities (name) values ('Buenavista-Quindí­o');
insert into cities (name) values ('Buenavista-Sucre');
insert into cities (name) values ('Buenos Aires-Cauca');
insert into cities (name) values ('Buesaco-Nariño');
insert into cities (name) values ('Buga-Valle del Cauca');
insert into cities (name) values ('Bugalagrande-Valle del Cauca');
insert into cities (name) values ('Burí­tica-Antioquia');
insert into cities (name) values ('Busbanza-Boyacá');
insert into cities (name) values ('Cabrera-Cundinamarca');
insert into cities (name) values ('Cabrera-Santander');
insert into cities (name) values ('Cabuyaro-Meta');
insert into cities (name) values ('Cachipay-Cundinamarca');
insert into cities (name) values ('Caicedo-Antioquia');
insert into cities (name) values ('Caicedonia-Valle del Cauca');
insert into cities (name) values ('Caimito-Sucre');
insert into cities (name) values ('Cajamarca-Tolima');
insert into cities (name) values ('Cajibí­o-Cauca');
insert into cities (name) values ('Cajicá-Cundinamarca');
insert into cities (name) values ('Calamar-Bolí­var');
insert into cities (name) values ('Calamar-Guaviare');
insert into cities (name) values ('Calarcá-Quindí­o');
insert into cities (name) values ('Caldas-Antioquia');
insert into cities (name) values ('Caldas-Boyacá');
insert into cities (name) values ('Caldono-Cauca');
insert into cities (name) values ('California-Santander');
insert into cities (name) values ('Calima (Darién)-Valle del Cauca');
insert into cities (name) values ('Caloto-Cauca');
insert into cities (name) values ('Calí­-Valle del Cauca');
insert into cities (name) values ('Campamento-Antioquia');
insert into cities (name) values ('Campo de la Cruz-Atlántico');
insert into cities (name) values ('Campoalegre-Huila');
insert into cities (name) values ('Campohermoso-Boyacá');
insert into cities (name) values ('Canalete-Córdoba');
insert into cities (name) values ('Candelaria-Atlántico');
insert into cities (name) values ('Candelaria-Valle del Cauca');
insert into cities (name) values ('Cantagallo-Bolí­var');
insert into cities (name) values ('Cantón de San Pablo-Chocó');
insert into cities (name) values ('Caparrapí­-Cundinamarca');
insert into cities (name) values ('Capitanejo-Santander');
insert into cities (name) values ('Caracolí­-Antioquia');
insert into cities (name) values ('Caramanta-Antioquia');
insert into cities (name) values ('Carcasí­-Santander');
insert into cities (name) values ('Carepa-Antioquia');
insert into cities (name) values ('Carmen de Apicalá-Tolima');
insert into cities (name) values ('Carmen de Carupa-Cundinamarca');
insert into cities (name) values ('Carmen de Viboral-Antioquia');
insert into cities (name) values ('Carmen del Darién (CURBARADí“)-Chocó');
insert into cities (name) values ('Carolina-Antioquia');
insert into cities (name) values ('Cartagena-Bolí­var');
insert into cities (name) values ('Cartagena del Chairá-Caquetá');
insert into cities (name) values ('Cartago-Valle del Cauca');
insert into cities (name) values ('Caruríº-Vaupés');
insert into cities (name) values ('Casabianca-Tolima');
insert into cities (name) values ('Castilla la Nueva-Meta');
insert into cities (name) values ('Caucasia-Antioquia');
insert into cities (name) values ('Cañasgordas-Antioquia');
insert into cities (name) values ('Cepita-Santander');
insert into cities (name) values ('Cereté-Córdoba');
insert into cities (name) values ('Cerinza-Boyacá');
insert into cities (name) values ('Cerrito-Santander');
insert into cities (name) values ('Cerro San Antonio-Magdalena');
insert into cities (name) values ('Chachaguí­-Nariño');
insert into cities (name) values ('Chaguaní­-Cundinamarca');
insert into cities (name) values ('Chalán-Sucre');
insert into cities (name) values ('Chaparral-Tolima');
insert into cities (name) values ('Charalá-Santander');
insert into cities (name) values ('Charta-Santander');
insert into cities (name) values ('Chigorodó-Antioquia');
insert into cities (name) values ('Chima-Santander');
insert into cities (name) values ('Chimichagua-Cesar');
insert into cities (name) values ('Chimá-Córdoba');
insert into cities (name) values ('Chinavita-Boyacá');
insert into cities (name) values ('Chinchiná-Caldas');
insert into cities (name) values ('Chinácota-Norte de Santander');
insert into cities (name) values ('Chiníº-Córdoba');
insert into cities (name) values ('Chipaque-Cundinamarca');
insert into cities (name) values ('Chipatá-Santander');
insert into cities (name) values ('Chiquinquirá-Boyacá');
insert into cities (name) values ('Chiriguaná-Cesar');
insert into cities (name) values ('Chiscas-Boyacá');
insert into cities (name) values ('Chita-Boyacá');
insert into cities (name) values ('Chitagá-Norte de Santander');
insert into cities (name) values ('Chitaraque-Boyacá');
insert into cities (name) values ('Chivatá-Boyacá');
insert into cities (name) values ('Chivolo-Magdalena');
insert into cities (name) values ('Choachí­-Cundinamarca');
insert into cities (name) values ('Chocontá-Cundinamarca');
insert into cities (name) values ('Chámeza-Casanare');
insert into cities (name) values ('Chí­a-Cundinamarca');
insert into cities (name) values ('Chí­quiza-Boyacá');
insert into cities (name) values ('Chí­vor-Boyacá');
insert into cities (name) values ('Cicuco-Bolí­var');
insert into cities (name) values ('Cimitarra-Santander');
insert into cities (name) values ('Circasia-Quindí­o');
insert into cities (name) values ('Cisneros-Antioquia');
insert into cities (name) values ('Ciénaga-Boyacá');
insert into cities (name) values ('Ciénaga-Magdalena');
insert into cities (name) values ('Ciénaga de Oro-Córdoba');
insert into cities (name) values ('Clemencia-Bolí­var');
insert into cities (name) values ('Cocorná-Antioquia');
insert into cities (name) values ('Coello-Tolima');
insert into cities (name) values ('Cogua-Cundinamarca');
insert into cities (name) values ('Colombia-Huila');
insert into cities (name) values ('Colosó (Ricaurte)-Sucre');
insert into cities (name) values ('Colón-Putumayo');
insert into cities (name) values ('Colón (Génova)-Nariño');
insert into cities (name) values ('Concepción-Antioquia');
insert into cities (name) values ('Concepción-Santander');
insert into cities (name) values ('Concordia-Antioquia');
insert into cities (name) values ('Concordia-Magdalena');
insert into cities (name) values ('Condoto-Chocó');
insert into cities (name) values ('Confines-Santander');
insert into cities (name) values ('Consaca-Nariño');
insert into cities (name) values ('Contadero-Nariño');
insert into cities (name) values ('Contratación-Santander');
insert into cities (name) values ('Convención-Norte de Santander');
insert into cities (name) values ('Copacabana-Antioquia');
insert into cities (name) values ('Coper-Boyacá');
insert into cities (name) values ('Cordobá-Quindí­o');
insert into cities (name) values ('Corinto-Cauca');
insert into cities (name) values ('Coromoro-Santander');
insert into cities (name) values ('Corozal-Sucre');
insert into cities (name) values ('Corrales-Boyacá');
insert into cities (name) values ('Cota-Cundinamarca');
insert into cities (name) values ('Cotorra-Córdoba');
insert into cities (name) values ('Covarachí­a-Boyacá');
insert into cities (name) values ('Coveñas-Sucre');
insert into cities (name) values ('Coyaima-Tolima');
insert into cities (name) values ('Cravo Norte-Arauca');
insert into cities (name) values ('Cuaspud (Carlosama)-Nariño');
insert into cities (name) values ('Cubarral-Meta');
insert into cities (name) values ('Cubará-Boyacá');
insert into cities (name) values ('Cucaita-Boyacá');
insert into cities (name) values ('Cucunubá-Cundinamarca');
insert into cities (name) values ('Cucutilla-Norte de Santander');
insert into cities (name) values ('Cuitiva-Boyacá');
insert into cities (name) values ('Cumaral-Meta');
insert into cities (name) values ('Cumaribo-Vichada');
insert into cities (name) values ('Cumbal-Nariño');
insert into cities (name) values ('Cumbitara-Nariño');
insert into cities (name) values ('Cunday-Tolima');
insert into cities (name) values ('Curillo-Caquetá');
insert into cities (name) values ('Curití­-Santander');
insert into cities (name) values ('Curumaní­-Cesar');
insert into cities (name) values ('Cáceres-Antioquia');
insert into cities (name) values ('Cáchira-Norte de Santander');
insert into cities (name) values ('Cácota-Norte de Santander');
insert into cities (name) values ('Cáqueza-Cundinamarca');
insert into cities (name) values ('Cértegui-Chocó');
insert into cities (name) values ('Cómbita-Boyacá');
insert into cities (name) values ('Córdoba-Bolí­var');
insert into cities (name) values ('Córdoba-Nariño');
insert into cities (name) values ('Cíºcuta-Norte de Santander');
insert into cities (name) values ('Dabeiba-Antioquia');
insert into cities (name) values ('Dagua-Valle del Cauca');
insert into cities (name) values ('Dibulla-La Guajira');
insert into cities (name) values ('Distracción-La Guajira');
insert into cities (name) values ('Dolores-Tolima');
insert into cities (name) values ('Don Matí­as-Antioquia');
insert into cities (name) values ('Dos Quebradas-Risaralda');
insert into cities (name) values ('Duitama-Boyacá');
insert into cities (name) values ('Durania-Norte de Santander');
insert into cities (name) values ('Ebéjico-Antioquia');
insert into cities (name) values ('El Bagre-Antioquia');
insert into cities (name) values ('El Banco-Magdalena');
insert into cities (name) values ('El Cairo-Valle del Cauca');
insert into cities (name) values ('El Calvario-Meta');
insert into cities (name) values ('El Carmen-Norte de Santander');
insert into cities (name) values ('El Carmen-Santander');
insert into cities (name) values ('El Carmen de Atrato-Chocó');
insert into cities (name) values ('El Carmen de Bolí­var-Bolí­var');
insert into cities (name) values ('El Castillo-Meta');
insert into cities (name) values ('El Cerrito-Valle del Cauca');
insert into cities (name) values ('El Charco-Nariño');
insert into cities (name) values ('El Cocuy-Boyacá');
insert into cities (name) values ('El Colegio-Cundinamarca');
insert into cities (name) values ('El Copey-Cesar');
insert into cities (name) values ('El Doncello-Caquetá');
insert into cities (name) values ('El Dorado-Meta');
insert into cities (name) values ('El Dovio-Valle del Cauca');
insert into cities (name) values ('El Espino-Boyacá');
insert into cities (name) values ('El Guacamayo-Santander');
insert into cities (name) values ('El Guamo-Bolí­var');
insert into cities (name) values ('El Molino-La Guajira');
insert into cities (name) values ('El Paso-Cesar');
insert into cities (name) values ('El Paujil-Caquetá');
insert into cities (name) values ('El Peñol-Nariño');
insert into cities (name) values ('El Peñon-Bolí­var');
insert into cities (name) values ('El Peñon-Santander');
insert into cities (name) values ('El Peñón-Cundinamarca');
insert into cities (name) values ('El Piñon-Magdalena');
insert into cities (name) values ('El Playón-Santander');
insert into cities (name) values ('El Retorno-Guaviare');
insert into cities (name) values ('El Retén-Magdalena');
insert into cities (name) values ('El Roble-Sucre');
insert into cities (name) values ('El Rosal-Cundinamarca');
insert into cities (name) values ('El Rosario-Nariño');
insert into cities (name) values ('El Tablón de Gómez-Nariño');
insert into cities (name) values ('El Tambo-Cauca');
insert into cities (name) values ('El Tambo-Nariño');
insert into cities (name) values ('El Tarra-Norte de Santander');
insert into cities (name) values ('El Zulia-Norte de Santander');
insert into cities (name) values ('El íguila-Valle del Cauca');
insert into cities (name) values ('Elí­as-Huila');
insert into cities (name) values ('Encino-Santander');
insert into cities (name) values ('Enciso-Santander');
insert into cities (name) values ('Entrerrí­os-Antioquia');
insert into cities (name) values ('Envigado-Antioquia');
insert into cities (name) values ('Espinal-Tolima');
insert into cities (name) values ('Facatativá-Cundinamarca');
insert into cities (name) values ('Falan-Tolima');
insert into cities (name) values ('Filadelfia-Caldas');
insert into cities (name) values ('Filandia-Quindí­o');
insert into cities (name) values ('Firavitoba-Boyacá');
insert into cities (name) values ('Flandes-Tolima');
insert into cities (name) values ('Florencia-Caquetá');
insert into cities (name) values ('Florencia-Cauca');
insert into cities (name) values ('Floresta-Boyacá');
insert into cities (name) values ('Florida-Valle del Cauca');
insert into cities (name) values ('Floridablanca-Santander');
insert into cities (name) values ('Florián-Santander');
insert into cities (name) values ('Fonseca-La Guajira');
insert into cities (name) values ('Fortíºl-Arauca');
insert into cities (name) values ('Fosca-Cundinamarca');
insert into cities (name) values ('Francisco Pizarro-Nariño');
insert into cities (name) values ('Fredonia-Antioquia');
insert into cities (name) values ('Fresno-Tolima');
insert into cities (name) values ('Frontino-Antioquia');
insert into cities (name) values ('Fuente de Oro-Meta');
insert into cities (name) values ('Fundación-Magdalena');
insert into cities (name) values ('Funes-Nariño');
insert into cities (name) values ('Funza-Cundinamarca');
insert into cities (name) values ('Fusagasugá-Cundinamarca');
insert into cities (name) values ('Fómeque-Cundinamarca');
insert into cities (name) values ('Fíºquene-Cundinamarca');
insert into cities (name) values ('Gachalá-Cundinamarca');
insert into cities (name) values ('Gachancipá-Cundinamarca');
insert into cities (name) values ('Gachantivá-Boyacá');
insert into cities (name) values ('Gachetá-Cundinamarca');
insert into cities (name) values ('Galapa-Atlántico');
insert into cities (name) values ('Galeras (Nueva Granada)-Sucre');
insert into cities (name) values ('Galán-Santander');
insert into cities (name) values ('Gama-Cundinamarca');
insert into cities (name) values ('Gamarra-Cesar');
insert into cities (name) values ('Garagoa-Boyacá');
insert into cities (name) values ('Garzón-Huila');
insert into cities (name) values ('Gigante-Huila');
insert into cities (name) values ('Ginebra-Valle del Cauca');
insert into cities (name) values ('Giraldo-Antioquia');
insert into cities (name) values ('Girardot-Cundinamarca');
insert into cities (name) values ('Girardota-Antioquia');
insert into cities (name) values ('Girón-Santander');
insert into cities (name) values ('Gonzalez-Cesar');
insert into cities (name) values ('Gramalote-Norte de Santander');
insert into cities (name) values ('Granada-Antioquia');
insert into cities (name) values ('Granada-Cundinamarca');
insert into cities (name) values ('Granada-Meta');
insert into cities (name) values ('Guaca-Santander');
insert into cities (name) values ('Guacamayas-Boyacá');
insert into cities (name) values ('Guacarí­-Valle del Cauca');
insert into cities (name) values ('Guachavés-Nariño');
insert into cities (name) values ('Guachené-Cauca');
insert into cities (name) values ('Guachetá-Cundinamarca');
insert into cities (name) values ('Guachucal-Nariño');
insert into cities (name) values ('Guadalupe-Antioquia');
insert into cities (name) values ('Guadalupe-Huila');
insert into cities (name) values ('Guadalupe-Santander');
insert into cities (name) values ('Guaduas-Cundinamarca');
insert into cities (name) values ('Guaitarilla-Nariño');
insert into cities (name) values ('Gualmatán-Nariño');
insert into cities (name) values ('Guamal-Magdalena');
insert into cities (name) values ('Guamal-Meta');
insert into cities (name) values ('Guamo-Tolima');
insert into cities (name) values ('Guapota-Santander');
insert into cities (name) values ('Guapí­-Cauca');
insert into cities (name) values ('Guaranda-Sucre');
insert into cities (name) values ('Guarne-Antioquia');
insert into cities (name) values ('Guasca-Cundinamarca');
insert into cities (name) values ('Guatapé-Antioquia');
insert into cities (name) values ('Guataquí­-Cundinamarca');
insert into cities (name) values ('Guatavita-Cundinamarca');
insert into cities (name) values ('Guateque-Boyacá');
insert into cities (name) values ('Guavatá-Santander');
insert into cities (name) values ('Guayabal de Siquima-Cundinamarca');
insert into cities (name) values ('Guayabetal-Cundinamarca');
insert into cities (name) values ('Guayatá-Boyacá');
insert into cities (name) values ('Guepsa-Santander');
insert into cities (name) values ('Guicán-Boyacá');
insert into cities (name) values ('Gutiérrez-Cundinamarca');
insert into cities (name) values ('Guática-Risaralda');
insert into cities (name) values ('Gámbita-Santander');
insert into cities (name) values ('Gámeza-Boyacá');
insert into cities (name) values ('Génova-Quindí­o');
insert into cities (name) values ('Gómez Plata-Antioquia');
insert into cities (name) values ('Hacarí­-Norte de Santander');
insert into cities (name) values ('Hatillo de Loba-Bolí­var');
insert into cities (name) values ('Hato-Santander');
insert into cities (name) values ('Hato Corozal-Casanare');
insert into cities (name) values ('Hatonuevo-La Guajira');
insert into cities (name) values ('Heliconia-Antioquia');
insert into cities (name) values ('Herrán-Norte de Santander');
insert into cities (name) values ('Herveo-Tolima');
insert into cities (name) values ('Hispania-Antioquia');
insert into cities (name) values ('Hobo-Huila');
insert into cities (name) values ('Honda-Tolima');
insert into cities (name) values ('Ibagué-Tolima');
insert into cities (name) values ('Icononzo-Tolima');
insert into cities (name) values ('Iles-Nariño');
insert into cities (name) values ('Imíºes-Nariño');
insert into cities (name) values ('Inzá-Cauca');
insert into cities (name) values ('Iní­rida-Guainí­a');
insert into cities (name) values ('Ipiales-Nariño');
insert into cities (name) values ('Isnos-Huila');
insert into cities (name) values ('Istmina-Chocó');
insert into cities (name) values ('Itagí¼í­-Antioquia');
insert into cities (name) values ('Ituango-Antioquia');
insert into cities (name) values ('Izá-Boyacá');
insert into cities (name) values ('Jambaló-Cauca');
insert into cities (name) values ('Jamundí­-Valle del Cauca');
insert into cities (name) values ('Jardí­n-Antioquia');
insert into cities (name) values ('Jenesano-Boyacá');
insert into cities (name) values ('Jericó-Antioquia');
insert into cities (name) values ('Jericó-Boyacá');
insert into cities (name) values ('Jerusalén-Cundinamarca');
insert into cities (name) values ('Jesíºs Marí­a-Santander');
insert into cities (name) values ('Jordán-Santander');
insert into cities (name) values ('Juan de Acosta-Atlántico');
insert into cities (name) values ('Juní­n-Cundinamarca');
insert into cities (name) values ('Juradó-Chocó');
insert into cities (name) values ('La Apartada y La Frontera-Córdoba');
insert into cities (name) values ('La Argentina-Huila');
insert into cities (name) values ('La Belleza-Santander');
insert into cities (name) values ('La Calera-Cundinamarca');
insert into cities (name) values ('La Capilla-Boyacá');
insert into cities (name) values ('La Ceja-Antioquia');
insert into cities (name) values ('La Celia-Risaralda');
insert into cities (name) values ('La Cruz-Nariño');
insert into cities (name) values ('La Cumbre-Valle del Cauca');
insert into cities (name) values ('La Dorada-Caldas');
insert into cities (name) values ('La Esperanza-Norte de Santander');
insert into cities (name) values ('La Estrella-Antioquia');
insert into cities (name) values ('La Florida-Nariño');
insert into cities (name) values ('La Gloria-Cesar');
insert into cities (name) values ('La Jagua de Ibirico-Cesar');
insert into cities (name) values ('La Jagua del Pilar-La Guajira');
insert into cities (name) values ('La Llanada-Nariño');
insert into cities (name) values ('La Macarena-Meta');
insert into cities (name) values ('La Merced-Caldas');
insert into cities (name) values ('La Mesa-Cundinamarca');
insert into cities (name) values ('La Montañita-Caquetá');
insert into cities (name) values ('La Palma-Cundinamarca');
insert into cities (name) values ('La Paz-Santander');
insert into cities (name) values ('La Paz (Robles)-Cesar');
insert into cities (name) values ('La Peña-Cundinamarca');
insert into cities (name) values ('La Pintada-Antioquia');
insert into cities (name) values ('La Plata-Huila');
insert into cities (name) values ('La Playa-Norte de Santander');
insert into cities (name) values ('La Primavera-Vichada');
insert into cities (name) values ('La Salina-Casanare');
insert into cities (name) values ('La Sierra-Cauca');
insert into cities (name) values ('La Tebaida-Quindí­o');
insert into cities (name) values ('La Tola-Nariño');
insert into cities (name) values ('La Unión-Antioquia');
insert into cities (name) values ('La Unión-Nariño');
insert into cities (name) values ('La Unión-Sucre');
insert into cities (name) values ('La Unión-Valle del Cauca');
insert into cities (name) values ('La Uvita-Boyacá');
insert into cities (name) values ('La Vega-Cauca');
insert into cities (name) values ('La Vega-Cundinamarca');
insert into cities (name) values ('La Victoria-Boyacá');
insert into cities (name) values ('La Victoria-Caldas');
insert into cities (name) values ('La Victoria-Valle del Cauca');
insert into cities (name) values ('La Virginia-Risaralda');
insert into cities (name) values ('Labateca-Norte de Santander');
insert into cities (name) values ('Labranzagrande-Boyacá');
insert into cities (name) values ('Landázuri-Santander');
insert into cities (name) values ('Lebrija-Santander');
insert into cities (name) values ('Leiva-Nariño');
insert into cities (name) values ('Lejaní­as-Meta');
insert into cities (name) values ('Lenguazaque-Cundinamarca');
insert into cities (name) values ('Leticia-Amazonas');
insert into cities (name) values ('Liborina-Antioquia');
insert into cities (name) values ('Linares-Nariño');
insert into cities (name) values ('Lloró-Chocó');
insert into cities (name) values ('Lorica-Córdoba');
insert into cities (name) values ('Los Córdobas-Córdoba');
insert into cities (name) values ('Los Palmitos-Sucre');
insert into cities (name) values ('Los Patios-Norte de Santander');
insert into cities (name) values ('Los Santos-Santander');
insert into cities (name) values ('Lourdes-Norte de Santander');
insert into cities (name) values ('Luruaco-Atlántico');
insert into cities (name) values ('Lérida-Tolima');
insert into cities (name) values ('Lí­bano-Tolima');
insert into cities (name) values ('López (Micay)-Cauca');
insert into cities (name) values ('Macanal-Boyacá');
insert into cities (name) values ('Macaravita-Santander');
insert into cities (name) values ('Maceo-Antioquia');
insert into cities (name) values ('Machetá-Cundinamarca');
insert into cities (name) values ('Madrid-Cundinamarca');
insert into cities (name) values ('Magangué-Bolí­var');
insert into cities (name) values ('Magí¼i (Payán)-Nariño');
insert into cities (name) values ('Mahates-Bolí­var');
insert into cities (name) values ('Maicao-La Guajira');
insert into cities (name) values ('Majagual-Sucre');
insert into cities (name) values ('Malambo-Atlántico');
insert into cities (name) values ('Mallama (Piedrancha)-Nariño');
insert into cities (name) values ('Manatí­-Atlántico');
insert into cities (name) values ('Manaure-La Guajira');
insert into cities (name) values ('Manaure Balcón del Cesar-Cesar');
insert into cities (name) values ('Manizales-Caldas');
insert into cities (name) values ('Manta-Cundinamarca');
insert into cities (name) values ('Manzanares-Caldas');
insert into cities (name) values ('Maní­-Casanare');
insert into cities (name) values ('Mapiripan-Meta');
insert into cities (name) values ('Margarita-Bolí­var');
insert into cities (name) values ('Marinilla-Antioquia');
insert into cities (name) values ('Maripí­-Boyacá');
insert into cities (name) values ('Mariquita-Tolima');
insert into cities (name) values ('Marmato-Caldas');
insert into cities (name) values ('Marquetalia-Caldas');
insert into cities (name) values ('Marsella-Risaralda');
insert into cities (name) values ('Marulanda-Caldas');
insert into cities (name) values ('Marí­a la Baja-Bolí­var');
insert into cities (name) values ('Matanza-Santander');
insert into cities (name) values ('Medellí­n-Antioquia');
insert into cities (name) values ('Medina-Cundinamarca');
insert into cities (name) values ('Medio Atrato-Chocó');
insert into cities (name) values ('Medio Baudó-Chocó');
insert into cities (name) values ('Medio San Juan (ANDAGOYA)-Chocó');
insert into cities (name) values ('Melgar-Tolima');
insert into cities (name) values ('Mercaderes-Cauca');
insert into cities (name) values ('Mesetas-Meta');
insert into cities (name) values ('Milán-Caquetá');
insert into cities (name) values ('Miraflores-Boyacá');
insert into cities (name) values ('Miraflores-Guaviare');
insert into cities (name) values ('Miranda-Cauca');
insert into cities (name) values ('Mistrató-Risaralda');
insert into cities (name) values ('Mitíº-Vaupés');
insert into cities (name) values ('Mocoa-Putumayo');
insert into cities (name) values ('Mogotes-Santander');
insert into cities (name) values ('Molagavita-Santander');
insert into cities (name) values ('Momil-Córdoba');
insert into cities (name) values ('Mompós-Bolí­var');
insert into cities (name) values ('Mongua-Boyacá');
insert into cities (name) values ('Monguí­-Boyacá');
insert into cities (name) values ('Moniquirá-Boyacá');
insert into cities (name) values ('Montebello-Antioquia');
insert into cities (name) values ('Montecristo-Bolí­var');
insert into cities (name) values ('Montelí­bano-Córdoba');
insert into cities (name) values ('Montenegro-Quindí­o');
insert into cities (name) values ('Monteria-Córdoba');
insert into cities (name) values ('Monterrey-Casanare');
insert into cities (name) values ('Morales-Bolí­var');
insert into cities (name) values ('Morales-Cauca');
insert into cities (name) values ('Morelia-Caquetá');
insert into cities (name) values ('Morroa-Sucre');
insert into cities (name) values ('Mosquera-Cundinamarca');
insert into cities (name) values ('Mosquera-Nariño');
insert into cities (name) values ('Motavita-Boyacá');
insert into cities (name) values ('Moñitos-Córdoba');
insert into cities (name) values ('Murillo-Tolima');
insert into cities (name) values ('Murindó-Antioquia');
insert into cities (name) values ('Mutatá-Antioquia');
insert into cities (name) values ('Mutiscua-Norte de Santander');
insert into cities (name) values ('Muzo-Boyacá');
insert into cities (name) values ('Málaga-Santander');
insert into cities (name) values ('Nariño-Antioquia');
insert into cities (name) values ('Nariño-Cundinamarca');
insert into cities (name) values ('Nariño-Nariño');
insert into cities (name) values ('Natagaima-Tolima');
insert into cities (name) values ('Nechí­-Antioquia');
insert into cities (name) values ('Necoclí­-Antioquia');
insert into cities (name) values ('Neira-Caldas');
insert into cities (name) values ('Neiva-Huila');
insert into cities (name) values ('Nemocón-Cundinamarca');
insert into cities (name) values ('Nilo-Cundinamarca');
insert into cities (name) values ('Nimaima-Cundinamarca');
insert into cities (name) values ('Nobsa-Boyacá');
insert into cities (name) values ('Nocaima-Cundinamarca');
insert into cities (name) values ('Norcasia-Caldas');
insert into cities (name) values ('Norosí­-Bolí­var');
insert into cities (name) values ('Novita-Chocó');
insert into cities (name) values ('Nueva Granada-Magdalena');
insert into cities (name) values ('Nuevo Colón-Boyacá');
insert into cities (name) values ('Nunchí­a-Casanare');
insert into cities (name) values ('Nuquí­-Chocó');
insert into cities (name) values ('Nátaga-Huila');
insert into cities (name) values ('Obando-Valle del Cauca');
insert into cities (name) values ('Ocamonte-Santander');
insert into cities (name) values ('Ocaña-Norte de Santander');
insert into cities (name) values ('Oiba-Santander');
insert into cities (name) values ('Oicatá-Boyacá');
insert into cities (name) values ('Olaya-Antioquia');
insert into cities (name) values ('Olaya Herrera-Nariño');
insert into cities (name) values ('Onzaga-Santander');
insert into cities (name) values ('Oporapa-Huila');
insert into cities (name) values ('Orito-Putumayo');
insert into cities (name) values ('Orocué-Casanare');
insert into cities (name) values ('Ortega-Tolima');
insert into cities (name) values ('Ospina-Nariño');
insert into cities (name) values ('Otanche-Boyacá');
insert into cities (name) values ('Ovejas-Sucre');
insert into cities (name) values ('Pachavita-Boyacá');
insert into cities (name) values ('Pacho-Cundinamarca');
insert into cities (name) values ('Padilla-Cauca');
insert into cities (name) values ('Paicol-Huila');
insert into cities (name) values ('Pailitas-Cesar');
insert into cities (name) values ('Paime-Cundinamarca');
insert into cities (name) values ('Paipa-Boyacá');
insert into cities (name) values ('Pajarito-Boyacá');
insert into cities (name) values ('Palermo-Huila');
insert into cities (name) values ('Palestina-Caldas');
insert into cities (name) values ('Palestina-Huila');
insert into cities (name) values ('Palmar-Santander');
insert into cities (name) values ('Palmar de Varela-Atlántico');
insert into cities (name) values ('Palmas del Socorro-Santander');
insert into cities (name) values ('Palmira-Valle del Cauca');
insert into cities (name) values ('Palmito-Sucre');
insert into cities (name) values ('Palocabildo-Tolima');
insert into cities (name) values ('Pamplona-Norte de Santander');
insert into cities (name) values ('Pamplonita-Norte de Santander');
insert into cities (name) values ('Pandi-Cundinamarca');
insert into cities (name) values ('Panqueba-Boyacá');
insert into cities (name) values ('Paratebueno-Cundinamarca');
insert into cities (name) values ('Pasca-Cundinamarca');
insert into cities (name) values ('Patí­a (El Bordo)-Cauca');
insert into cities (name) values ('Pauna-Boyacá');
insert into cities (name) values ('Paya-Boyacá');
insert into cities (name) values ('Paz de Ariporo-Casanare');
insert into cities (name) values ('Paz de Rí­o-Boyacá');
insert into cities (name) values ('Pedraza-Magdalena');
insert into cities (name) values ('Pelaya-Cesar');
insert into cities (name) values ('Pensilvania-Caldas');
insert into cities (name) values ('Peque-Antioquia');
insert into cities (name) values ('Pereira-Risaralda');
insert into cities (name) values ('Pesca-Boyacá');
insert into cities (name) values ('Peñol-Antioquia');
insert into cities (name) values ('Piamonte-Cauca');
insert into cities (name) values ('Pie de Cuesta-Santander');
insert into cities (name) values ('Piedras-Tolima');
insert into cities (name) values ('Piendamó-Cauca');
insert into cities (name) values ('Pijao-Quindí­o');
insert into cities (name) values ('Pijiño-Magdalena');
insert into cities (name) values ('Pinchote-Santander');
insert into cities (name) values ('Pinillos-Bolí­var');
insert into cities (name) values ('Piojo-Atlántico');
insert into cities (name) values ('Pisva-Boyacá');
insert into cities (name) values ('Pital-Huila');
insert into cities (name) values ('Pitalito-Huila');
insert into cities (name) values ('Pivijay-Magdalena');
insert into cities (name) values ('Planadas-Tolima');
insert into cities (name) values ('Planeta Rica-Córdoba');
insert into cities (name) values ('Plato-Magdalena');
insert into cities (name) values ('Policarpa-Nariño');
insert into cities (name) values ('Polonuevo-Atlántico');
insert into cities (name) values ('Ponedera-Atlántico');
insert into cities (name) values ('Popayán-Cauca');
insert into cities (name) values ('Pore-Casanare');
insert into cities (name) values ('Potosí­-Nariño');
insert into cities (name) values ('Pradera-Valle del Cauca');
insert into cities (name) values ('Prado-Tolima');
insert into cities (name) values ('Providencia-Nariño');
insert into cities (name) values ('Providencia-San Andrés');
insert into cities (name) values ('Pueblo Bello-Cesar');
insert into cities (name) values ('Pueblo Nuevo-Córdoba');
insert into cities (name) values ('Pueblo Rico-Risaralda');
insert into cities (name) values ('Pueblorrico-Antioquia');
insert into cities (name) values ('Puebloviejo-Magdalena');
insert into cities (name) values ('Puente Nacional-Santander');
insert into cities (name) values ('Puerres-Nariño');
insert into cities (name) values ('Puerto Así­s-Putumayo');
insert into cities (name) values ('Puerto Berrí­o-Antioquia');
insert into cities (name) values ('Puerto Boyacá-Boyacá');
insert into cities (name) values ('Puerto Caicedo-Putumayo');
insert into cities (name) values ('Puerto Carreño-Vichada');
insert into cities (name) values ('Puerto Colombia-Atlántico');
insert into cities (name) values ('Puerto Concordia-Meta');
insert into cities (name) values ('Puerto Escondido-Córdoba');
insert into cities (name) values ('Puerto Gaitán-Meta');
insert into cities (name) values ('Puerto Guzmán-Putumayo');
insert into cities (name) values ('Puerto Leguí­zamo-Putumayo');
insert into cities (name) values ('Puerto Libertador-Córdoba');
insert into cities (name) values ('Puerto Lleras-Meta');
insert into cities (name) values ('Puerto López-Meta');
insert into cities (name) values ('Puerto Nare-Antioquia');
insert into cities (name) values ('Puerto Nariño-Amazonas');
insert into cities (name) values ('Puerto Parra-Santander');
insert into cities (name) values ('Puerto Rico-Caquetá');
insert into cities (name) values ('Puerto Rico-Meta');
insert into cities (name) values ('Puerto Rondón-Arauca');
insert into cities (name) values ('Puerto Salgar-Cundinamarca');
insert into cities (name) values ('Puerto Santander-Norte de Santander');
insert into cities (name) values ('Puerto Tejada-Cauca');
insert into cities (name) values ('Puerto Triunfo-Antioquia');
insert into cities (name) values ('Puerto Wilches-Santander');
insert into cities (name) values ('Pulí­-Cundinamarca');
insert into cities (name) values ('Pupiales-Nariño');
insert into cities (name) values ('Puracé (Coconuco)-Cauca');
insert into cities (name) values ('Purificación-Tolima');
insert into cities (name) values ('Purí­sima-Córdoba');
insert into cities (name) values ('Pácora-Caldas');
insert into cities (name) values ('Páez-Boyacá');
insert into cities (name) values ('Páez (Belalcazar)-Cauca');
insert into cities (name) values ('Páramo-Santander');
insert into cities (name) values ('Quebradanegra-Cundinamarca');
insert into cities (name) values ('Quetame-Cundinamarca');
insert into cities (name) values ('Quibdó-Chocó');
insert into cities (name) values ('Quimbaya-Quindí­o');
insert into cities (name) values ('Quinchí­a-Risaralda');
insert into cities (name) values ('Quipama-Boyacá');
insert into cities (name) values ('Quipile-Cundinamarca');
insert into cities (name) values ('Ragonvalia-Norte de Santander');
insert into cities (name) values ('Ramiriquí­-Boyacá');
insert into cities (name) values ('Recetor-Casanare');
insert into cities (name) values ('Regidor-Bolí­var');
insert into cities (name) values ('Remedios-Antioquia');
insert into cities (name) values ('Remolino-Magdalena');
insert into cities (name) values ('Repelón-Atlántico');
insert into cities (name) values ('Restrepo-Meta');
insert into cities (name) values ('Restrepo-Valle del Cauca');
insert into cities (name) values ('Retiro-Antioquia');
insert into cities (name) values ('Ricaurte-Cundinamarca');
insert into cities (name) values ('Ricaurte-Nariño');
insert into cities (name) values ('Rio Negro-Santander');
insert into cities (name) values ('Rioblanco-Tolima');
insert into cities (name) values ('Riofrí­o-Valle del Cauca');
insert into cities (name) values ('Riohacha-La Guajira');
insert into cities (name) values ('Risaralda-Caldas');
insert into cities (name) values ('Rivera-Huila');
insert into cities (name) values ('Roberto Payán (San José)-Nariño');
insert into cities (name) values ('Roldanillo-Valle del Cauca');
insert into cities (name) values ('Roncesvalles-Tolima');
insert into cities (name) values ('Rondón-Boyacá');
insert into cities (name) values ('Rosas-Cauca');
insert into cities (name) values ('Rovira-Tolima');
insert into cities (name) values ('Ráquira-Boyacá');
insert into cities (name) values ('Rí­o Iró-Chocó');
insert into cities (name) values ('Rí­o Quito-Chocó');
insert into cities (name) values ('Rí­o Sucio-Caldas');
insert into cities (name) values ('Rí­o Viejo-Bolí­var');
insert into cities (name) values ('Rí­o de oro-Cesar');
insert into cities (name) values ('Rí­onegro-Antioquia');
insert into cities (name) values ('Rí­osucio-Chocó');
insert into cities (name) values ('Sabana de Torres-Santander');
insert into cities (name) values ('Sabanagrande-Atlántico');
insert into cities (name) values ('Sabanalarga-Antioquia');
insert into cities (name) values ('Sabanalarga-Atlántico');
insert into cities (name) values ('Sabanalarga-Casanare');
insert into cities (name) values ('Sabanas de San Angel (SAN ANGEL)-Magdalena');
insert into cities (name) values ('Sabaneta-Antioquia');
insert into cities (name) values ('Saboyá-Boyacá');
insert into cities (name) values ('Sahagíºn-Córdoba');
insert into cities (name) values ('Saladoblanco-Huila');
insert into cities (name) values ('Salamina-Caldas');
insert into cities (name) values ('Salamina-Magdalena');
insert into cities (name) values ('Salazar-Norte de Santander');
insert into cities (name) values ('Saldaña-Tolima');
insert into cities (name) values ('Salento-Quindí­o');
insert into cities (name) values ('Salgar-Antioquia');
insert into cities (name) values ('Samacá-Boyacá');
insert into cities (name) values ('Samaniego-Nariño');
insert into cities (name) values ('Samaná-Caldas');
insert into cities (name) values ('Sampués-Sucre');
insert into cities (name) values ('San Agustí­n-Huila');
insert into cities (name) values ('San Alberto-Cesar');
insert into cities (name) values ('San Andrés-Santander');
insert into cities (name) values ('San Andrés Sotavento-Córdoba');
insert into cities (name) values ('San Andrés de Cuerquí­a-Antioquia');
insert into cities (name) values ('San Antero-Córdoba');
insert into cities (name) values ('San Antonio-Tolima');
insert into cities (name) values ('San Antonio de Tequendama-Cundinamarca');
insert into cities (name) values ('San Benito-Santander');
insert into cities (name) values ('San Benito Abad-Sucre');
insert into cities (name) values ('San Bernardo-Cundinamarca');
insert into cities (name) values ('San Bernardo-Nariño');
insert into cities (name) values ('San Bernardo del Viento-Córdoba');
insert into cities (name) values ('San Calixto-Norte de Santander');
insert into cities (name) values ('San Carlos-Antioquia');
insert into cities (name) values ('San Carlos-Córdoba');
insert into cities (name) values ('San Carlos de Guaroa-Meta');
insert into cities (name) values ('San Cayetano-Cundinamarca');
insert into cities (name) values ('San Cayetano-Norte de Santander');
insert into cities (name) values ('San Cristobal-Bolí­var');
insert into cities (name) values ('San Diego-Cesar');
insert into cities (name) values ('San Eduardo-Boyacá');
insert into cities (name) values ('San Estanislao-Bolí­var');
insert into cities (name) values ('San Fernando-Bolí­var');
insert into cities (name) values ('San Francisco-Antioquia');
insert into cities (name) values ('San Francisco-Cundinamarca');
insert into cities (name) values ('San Francisco-Putumayo');
insert into cities (name) values ('San Gí­l-Santander');
insert into cities (name) values ('San Jacinto-Bolí­var');
insert into cities (name) values ('San Jacinto del Cauca-Bolí­var');
insert into cities (name) values ('San Jerónimo-Antioquia');
insert into cities (name) values ('San Joaquí­n-Santander');
insert into cities (name) values ('San José-Caldas');
insert into cities (name) values ('San José de Miranda-Santander');
insert into cities (name) values ('San José de Montaña-Antioquia');
insert into cities (name) values ('San José de Pare-Boyacá');
insert into cities (name) values ('San José de Uré-Córdoba');
insert into cities (name) values ('San José del Fragua-Caquetá');
insert into cities (name) values ('San José del Guaviare-Guaviare');
insert into cities (name) values ('San José del Palmar-Chocó');
insert into cities (name) values ('San Juan de Arama-Meta');
insert into cities (name) values ('San Juan de Betulia-Sucre');
insert into cities (name) values ('San Juan de Nepomuceno-Bolí­var');
insert into cities (name) values ('San Juan de Pasto-Nariño');
insert into cities (name) values ('San Juan de Rí­o Seco-Cundinamarca');
insert into cities (name) values ('San Juan de Urabá-Antioquia');
insert into cities (name) values ('San Juan del Cesar-La Guajira');
insert into cities (name) values ('San Juanito-Meta');
insert into cities (name) values ('San Lorenzo-Nariño');
insert into cities (name) values ('San Luis-Tolima');
insert into cities (name) values ('San Luí­s-Antioquia');
insert into cities (name) values ('San Luí­s de Gaceno-Boyacá');
insert into cities (name) values ('San Luí­s de Palenque-Casanare');
insert into cities (name) values ('San Marcos-Sucre');
insert into cities (name) values ('San Martí­n-Cesar');
insert into cities (name) values ('San Martí­n-Meta');
insert into cities (name) values ('San Martí­n de Loba-Bolí­var');
insert into cities (name) values ('San Mateo-Boyacá');
insert into cities (name) values ('San Miguel-Santander');
insert into cities (name) values ('San Miguel-Putumayo');
insert into cities (name) values ('San Miguel de Sema-Boyacá');
insert into cities (name) values ('San Onofre-Sucre');
insert into cities (name) values ('San Pablo-Bolí­var');
insert into cities (name) values ('San Pablo-Nariño');
insert into cities (name) values ('San Pablo de Borbur-Boyacá');
insert into cities (name) values ('San Pedro-Antioquia');
insert into cities (name) values ('San Pedro-Sucre');
insert into cities (name) values ('San Pedro-Valle del Cauca');
insert into cities (name) values ('San Pedro de Cartago-Nariño');
insert into cities (name) values ('San Pedro de Urabá-Antioquia');
insert into cities (name) values ('San Pelayo-Córdoba');
insert into cities (name) values ('San Rafael-Antioquia');
insert into cities (name) values ('San Roque-Antioquia');
insert into cities (name) values ('San Sebastián-Cauca');
insert into cities (name) values ('San Sebastián de Buenavista-Magdalena');
insert into cities (name) values ('San Vicente-Antioquia');
insert into cities (name) values ('San Vicente del Caguán-Caquetá');
insert into cities (name) values ('San Vicente del Chucurí­-Santander');
insert into cities (name) values ('San Zenón-Magdalena');
insert into cities (name) values ('Sandoná-Nariño');
insert into cities (name) values ('Santa Ana-Magdalena');
insert into cities (name) values ('Santa Bárbara-Antioquia');
insert into cities (name) values ('Santa Bárbara-Santander');
insert into cities (name) values ('Santa Bárbara (Iscuandé)-Nariño');
insert into cities (name) values ('Santa Bárbara de Pinto-Magdalena');
insert into cities (name) values ('Santa Catalina-Bolí­var');
insert into cities (name) values ('Santa Fé de Antioquia-Antioquia');
insert into cities (name) values ('Santa Genoveva de Docorodó-Chocó');
insert into cities (name) values ('Santa Helena del Opón-Santander');
insert into cities (name) values ('Santa Isabel-Tolima');
insert into cities (name) values ('Santa Lucí­a-Atlántico');
insert into cities (name) values ('Santa Marta-Magdalena');
insert into cities (name) values ('Santa Marí­a-Boyacá');
insert into cities (name) values ('Santa Marí­a-Huila');
insert into cities (name) values ('Santa Rosa-Bolí­var');
insert into cities (name) values ('Santa Rosa-Cauca');
insert into cities (name) values ('Santa Rosa de Cabal-Risaralda');
insert into cities (name) values ('Santa Rosa de Osos-Antioquia');
insert into cities (name) values ('Santa Rosa de Viterbo-Boyacá');
insert into cities (name) values ('Santa Rosa del Sur-Bolí­var');
insert into cities (name) values ('Santa Rosalí­a-Vichada');
insert into cities (name) values ('Santa Sofí­a-Boyacá');
insert into cities (name) values ('Santana-Boyacá');
insert into cities (name) values ('Santander de Quilichao-Cauca');
insert into cities (name) values ('Santiago-Norte de Santander');
insert into cities (name) values ('Santiago-Putumayo');
insert into cities (name) values ('Santo Domingo-Antioquia');
insert into cities (name) values ('Santo Tomás-Atlántico');
insert into cities (name) values ('Santuario-Antioquia');
insert into cities (name) values ('Santuario-Risaralda');
insert into cities (name) values ('Sapuyes-Nariño');
insert into cities (name) values ('Saravena-Arauca');
insert into cities (name) values ('Sardinata-Norte de Santander');
insert into cities (name) values ('Sasaima-Cundinamarca');
insert into cities (name) values ('Sativanorte-Boyacá');
insert into cities (name) values ('Sativasur-Boyacá');
insert into cities (name) values ('Segovia-Antioquia');
insert into cities (name) values ('Sesquilé-Cundinamarca');
insert into cities (name) values ('Sevilla-Valle del Cauca');
insert into cities (name) values ('Siachoque-Boyacá');
insert into cities (name) values ('Sibaté-Cundinamarca');
insert into cities (name) values ('Sibundoy-Putumayo');
insert into cities (name) values ('Silos-Norte de Santander');
insert into cities (name) values ('Silvania-Cundinamarca');
insert into cities (name) values ('Silvia-Cauca');
insert into cities (name) values ('Simacota-Santander');
insert into cities (name) values ('Simijaca-Cundinamarca');
insert into cities (name) values ('Simití­-Bolí­var');
insert into cities (name) values ('Sincelejo-Sucre');
insert into cities (name) values ('Sincé-Sucre');
insert into cities (name) values ('Sipí­-Chocó');
insert into cities (name) values ('Sitionuevo-Magdalena');
insert into cities (name) values ('Soacha-Cundinamarca');
insert into cities (name) values ('Soatá-Boyacá');
insert into cities (name) values ('Socha-Boyacá');
insert into cities (name) values ('Socorro-Santander');
insert into cities (name) values ('Socotá-Boyacá');
insert into cities (name) values ('Sogamoso-Boyacá');
insert into cities (name) values ('Solano-Caquetá');
insert into cities (name) values ('Soledad-Atlántico');
insert into cities (name) values ('Solita-Caquetá');
insert into cities (name) values ('Somondoco-Boyacá');
insert into cities (name) values ('Sonsón-Antioquia');
insert into cities (name) values ('Sopetrán-Antioquia');
insert into cities (name) values ('Soplaviento-Bolí­var');
insert into cities (name) values ('Sopó-Cundinamarca');
insert into cities (name) values ('Sora-Boyacá');
insert into cities (name) values ('Soracá-Boyacá');
insert into cities (name) values ('Sotaquirá-Boyacá');
insert into cities (name) values ('Sotara (Paispamba)-Cauca');
insert into cities (name) values ('Sotomayor (Los Andes)-Nariño');
insert into cities (name) values ('Suaita-Santander');
insert into cities (name) values ('Suan-Atlántico');
insert into cities (name) values ('Suaza-Huila');
insert into cities (name) values ('Subachoque-Cundinamarca');
insert into cities (name) values ('Sucre-Cauca');
insert into cities (name) values ('Sucre-Santander');
insert into cities (name) values ('Sucre-Sucre');
insert into cities (name) values ('Suesca-Cundinamarca');
insert into cities (name) values ('Supatá-Cundinamarca');
insert into cities (name) values ('Supí­a-Caldas');
insert into cities (name) values ('Suratá-Santander');
insert into cities (name) values ('Susa-Cundinamarca');
insert into cities (name) values ('Susacón-Boyacá');
insert into cities (name) values ('Sutamarchán-Boyacá');
insert into cities (name) values ('Sutatausa-Cundinamarca');
insert into cities (name) values ('Sutatenza-Boyacá');
insert into cities (name) values ('Suárez-Cauca');
insert into cities (name) values ('Suárez-Tolima');
insert into cities (name) values ('Sácama-Casanare');
insert into cities (name) values ('Sáchica-Boyacá');
insert into cities (name) values ('Tabio-Cundinamarca');
insert into cities (name) values ('Tadó-Chocó');
insert into cities (name) values ('Talaigua Nuevo-Bolí­var');
insert into cities (name) values ('Tamalameque-Cesar');
insert into cities (name) values ('Tame-Arauca');
insert into cities (name) values ('Taminango-Nariño');
insert into cities (name) values ('Tangua-Nariño');
insert into cities (name) values ('Taraira-Vaupés');
insert into cities (name) values ('Tarazá-Antioquia');
insert into cities (name) values ('Tarqui-Huila');
insert into cities (name) values ('Tarso-Antioquia');
insert into cities (name) values ('Tasco-Boyacá');
insert into cities (name) values ('Tauramena-Casanare');
insert into cities (name) values ('Tausa-Cundinamarca');
insert into cities (name) values ('Tello-Huila');
insert into cities (name) values ('Tena-Cundinamarca');
insert into cities (name) values ('Tenerife-Magdalena');
insert into cities (name) values ('Tenjo-Cundinamarca');
insert into cities (name) values ('Tenza-Boyacá');
insert into cities (name) values ('Teorama-Norte de Santander');
insert into cities (name) values ('Teruel-Huila');
insert into cities (name) values ('Tesalia-Huila');
insert into cities (name) values ('Tibacuy-Cundinamarca');
insert into cities (name) values ('Tibaná-Boyacá');
insert into cities (name) values ('Tibasosa-Boyacá');
insert into cities (name) values ('Tibirita-Cundinamarca');
insert into cities (name) values ('Tibíº-Norte de Santander');
insert into cities (name) values ('Tierralta-Córdoba');
insert into cities (name) values ('Timaná-Huila');
insert into cities (name) values ('Timbiquí­-Cauca');
insert into cities (name) values ('Timbí­o-Cauca');
insert into cities (name) values ('Tinjacá-Boyacá');
insert into cities (name) values ('Tipacoque-Boyacá');
insert into cities (name) values ('Tiquisio (Puerto Rico)-Bolí­var');
insert into cities (name) values ('Titiribí­-Antioquia');
insert into cities (name) values ('Toca-Boyacá');
insert into cities (name) values ('Tocaima-Cundinamarca');
insert into cities (name) values ('Tocancipá-Cundinamarca');
insert into cities (name) values ('Toguí­-Boyacá');
insert into cities (name) values ('Toledo-Antioquia');
insert into cities (name) values ('Toledo-Norte de Santander');
insert into cities (name) values ('Tolíº-Sucre');
insert into cities (name) values ('Tolíº Viejo-Sucre');
insert into cities (name) values ('Tona-Santander');
insert into cities (name) values ('Topagá-Boyacá');
insert into cities (name) values ('Topaipí­-Cundinamarca');
insert into cities (name) values ('Toribí­o-Cauca');
insert into cities (name) values ('Toro-Valle del Cauca');
insert into cities (name) values ('Tota-Boyacá');
insert into cities (name) values ('Totoró-Cauca');
insert into cities (name) values ('Trinidad-Casanare');
insert into cities (name) values ('Trujillo-Valle del Cauca');
insert into cities (name) values ('Tubará-Atlántico');
insert into cities (name) values ('Tuchí­n-Córdoba');
insert into cities (name) values ('Tulíºa-Valle del Cauca');
insert into cities (name) values ('Tumaco-Nariño');
insert into cities (name) values ('Tunja-Boyacá');
insert into cities (name) values ('Tunungua-Boyacá');
insert into cities (name) values ('Turbaco-Bolí­var');
insert into cities (name) values ('Turbaná-Bolí­var');
insert into cities (name) values ('Turbo-Antioquia');
insert into cities (name) values ('Turmequé-Boyacá');
insert into cities (name) values ('Tuta-Boyacá');
insert into cities (name) values ('Tutasá-Boyacá');
insert into cities (name) values ('Támara-Casanare');
insert into cities (name) values ('Támesis-Antioquia');
insert into cities (name) values ('Tíºquerres-Nariño');
insert into cities (name) values ('Ubalá-Cundinamarca');
insert into cities (name) values ('Ubaque-Cundinamarca');
insert into cities (name) values ('Ubaté-Cundinamarca');
insert into cities (name) values ('Ulloa-Valle del Cauca');
insert into cities (name) values ('Une-Cundinamarca');
insert into cities (name) values ('Unguí­a-Chocó');
insert into cities (name) values ('Unión Panamericana (íNIMAS)-Chocó');
insert into cities (name) values ('Uramita-Antioquia');
insert into cities (name) values ('Uribe-Meta');
insert into cities (name) values ('Uribia-La Guajira');
insert into cities (name) values ('Urrao-Antioquia');
insert into cities (name) values ('Urumita-La Guajira');
insert into cities (name) values ('Usiacuri-Atlántico');
insert into cities (name) values ('Valdivia-Antioquia');
insert into cities (name) values ('Valencia-Córdoba');
insert into cities (name) values ('Valle de San José-Santander');
insert into cities (name) values ('Valle de San Juan-Tolima');
insert into cities (name) values ('Valle del Guamuez-Putumayo');
insert into cities (name) values ('Valledupar-Cesar');
insert into cities (name) values ('Valparaiso-Antioquia');
insert into cities (name) values ('Valparaiso-Caquetá');
insert into cities (name) values ('Vegachí­-Antioquia');
insert into cities (name) values ('Venadillo-Tolima');
insert into cities (name) values ('Venecia-Antioquia');
insert into cities (name) values ('Venecia (Ospina Pérez)-Cundinamarca');
insert into cities (name) values ('Ventaquemada-Boyacá');
insert into cities (name) values ('Vergara-Cundinamarca');
insert into cities (name) values ('Versalles-Valle del Cauca');
insert into cities (name) values ('Vetas-Santander');
insert into cities (name) values ('Viani-Cundinamarca');
insert into cities (name) values ('Vigí­a del Fuerte-Antioquia');
insert into cities (name) values ('Vijes-Valle del Cauca');
insert into cities (name) values ('Villa Caro-Norte de Santander');
insert into cities (name) values ('Villa Rica-Cauca');
insert into cities (name) values ('Villa de Leiva-Boyacá');
insert into cities (name) values ('Villa del Rosario-Norte de Santander');
insert into cities (name) values ('Villagarzón-Putumayo');
insert into cities (name) values ('Villagómez-Cundinamarca');
insert into cities (name) values ('Villahermosa-Tolima');
insert into cities (name) values ('Villamarí­a-Caldas');
insert into cities (name) values ('Villanueva-Bolí­var');
insert into cities (name) values ('Villanueva-La Guajira');
insert into cities (name) values ('Villanueva-Santander');
insert into cities (name) values ('Villanueva-Casanare');
insert into cities (name) values ('Villapinzón-Cundinamarca');
insert into cities (name) values ('Villarrica-Tolima');
insert into cities (name) values ('Villavicencio-Meta');
insert into cities (name) values ('Villavieja-Huila');
insert into cities (name) values ('Villeta-Cundinamarca');
insert into cities (name) values ('Viotá-Cundinamarca');
insert into cities (name) values ('Viracachá-Boyacá');
insert into cities (name) values ('Vista Hermosa-Meta');
insert into cities (name) values ('Viterbo-Caldas');
insert into cities (name) values ('Vélez-Santander');
insert into cities (name) values ('Yacopí­-Cundinamarca');
insert into cities (name) values ('Yacuanquer-Nariño');
insert into cities (name) values ('Yaguará-Huila');
insert into cities (name) values ('Yalí­-Antioquia');
insert into cities (name) values ('Yarumal-Antioquia');
insert into cities (name) values ('Yolombó-Antioquia');
insert into cities (name) values ('Yondó (Casabe)-Antioquia');
insert into cities (name) values ('Yopal-Casanare');
insert into cities (name) values ('Yotoco-Valle del Cauca');
insert into cities (name) values ('Yumbo-Valle del Cauca');
insert into cities (name) values ('Zambrano-Bolí­var');
insert into cities (name) values ('Zapatoca-Santander');
insert into cities (name) values ('Zapayán (PUNTA DE PIEDRAS)-Magdalena');
insert into cities (name) values ('Zaragoza-Antioquia');
insert into cities (name) values ('Zarzal-Valle del Cauca');
insert into cities (name) values ('Zetaquirá-Boyacá');
insert into cities (name) values ('Zipacón-Cundinamarca');
insert into cities (name) values ('Zipaquirá-Cundinamarca');
insert into cities (name) values ('Zona Bananera (PRADO - SEVILLA)-Magdalena');
insert into cities (name) values ('íbrego-Norte de Santander');
insert into cities (name) values ('íquira-Huila');
insert into cities (name) values ('úmbita-Boyacá');
insert into cities (name) values ('útica-Cundinamarca');
