insert into cities (name) values ('Antioquia-Abejorral');
insert into cities (name) values ('Antioquia-Abriaquí­');
insert into cities (name) values ('Meta-Acací­as');
insert into cities (name) values ('Chocó-Acandí­');
insert into cities (name) values ('Huila-Acevedo');
insert into cities (name) values ('Bolí­var-Achí­');
insert into cities (name) values ('Huila-Agrado');
insert into cities (name) values ('Cundinamarca-Agua de Dios');
insert into cities (name) values ('Cesar-Aguachica');
insert into cities (name) values ('Santander-Aguada');
insert into cities (name) values ('Caldas-Aguadas');
insert into cities (name) values ('Casanare-Aguazul');
insert into cities (name) values ('Cesar-Agustí­n Codazzi');
insert into cities (name) values ('Huila-Aipe');
insert into cities (name) values ('Caquetá-Albania');
insert into cities (name) values ('La Guajira-Albania');
insert into cities (name) values ('Santander-Albania');
insert into cities (name) values ('Cundinamarca-Albán');
insert into cities (name) values ('Nariño-Albán (San José)');
insert into cities (name) values ('Valle del Cauca-Alcalá');
insert into cities (name) values ('Nariño-Aldana');
insert into cities (name) values ('Antioquia-Alejandria');
insert into cities (name) values ('Magdalena-Algarrobo');
insert into cities (name) values ('Huila-Algeciras');
insert into cities (name) values ('Cauca-Almaguer');
insert into cities (name) values ('Boyacá-Almeida');
insert into cities (name) values ('Tolima-Alpujarra');
insert into cities (name) values ('Huila-Altamira');
insert into cities (name) values ('Chocó-Alto Baudó (Pie de Pato)');
insert into cities (name) values ('Bolí­var-Altos del Rosario');
insert into cities (name) values ('Tolima-Alvarado');
insert into cities (name) values ('Antioquia-Amagá');
insert into cities (name) values ('Antioquia-Amalfi');
insert into cities (name) values ('Tolima-Ambalema');
insert into cities (name) values ('Cundinamarca-Anapoima');
insert into cities (name) values ('Nariño-Ancuya');
insert into cities (name) values ('Valle del Cauca-Andalucí­a');
insert into cities (name) values ('Antioquia-Andes');
insert into cities (name) values ('Antioquia-Angelópolis');
insert into cities (name) values ('Antioquia-Angostura');
insert into cities (name) values ('Cundinamarca-Anolaima');
insert into cities (name) values ('Antioquia-Anorí­');
insert into cities (name) values ('Caldas-Anserma');
insert into cities (name) values ('Valle del Cauca-Ansermanuevo');
insert into cities (name) values ('Tolima-Anzoátegui');
insert into cities (name) values ('Antioquia-Anzá');
insert into cities (name) values ('Antioquia-Apartadó');
insert into cities (name) values ('Cundinamarca-Apulo');
insert into cities (name) values ('Risaralda-Apí­a');
insert into cities (name) values ('Boyacá-Aquitania');
insert into cities (name) values ('Magdalena-Aracataca');
insert into cities (name) values ('Caldas-Aranzazu');
insert into cities (name) values ('Santander-Aratoca');
insert into cities (name) values ('Arauca-Arauca');
insert into cities (name) values ('Arauca-Arauquita');
insert into cities (name) values ('Cundinamarca-Arbeláez');
insert into cities (name) values ('Nariño-Arboleda (Berruecos)');
insert into cities (name) values ('Norte de Santander-Arboledas');
insert into cities (name) values ('Antioquia-Arboletes');
insert into cities (name) values ('Boyacá-Arcabuco');
insert into cities (name) values ('Bolí­var-Arenal');
insert into cities (name) values ('Antioquia-Argelia');
insert into cities (name) values ('Cauca-Argelia');
insert into cities (name) values ('Valle del Cauca-Argelia');
insert into cities (name) values ('Magdalena-Ariguaní­ (El Difí­cil)');
insert into cities (name) values ('Bolí­var-Arjona');
insert into cities (name) values ('Antioquia-Armenia');
insert into cities (name) values ('Quindí­o-Armenia');
insert into cities (name) values ('Tolima-Armero (Guayabal)');
insert into cities (name) values ('Bolí­var-Arroyohondo');
insert into cities (name) values ('Cesar-Astrea');
insert into cities (name) values ('Tolima-Ataco');
insert into cities (name) values ('Chocó-Atrato (Yuto)');
insert into cities (name) values ('Córdoba-Ayapel');
insert into cities (name) values ('Chocó-Bagadó');
insert into cities (name) values ('Chocó-Bahí­a Solano (Míºtis)');
insert into cities (name) values ('Chocó-Bajo Baudó (Pizarro)');
insert into cities (name) values ('Cauca-Balboa');
insert into cities (name) values ('Risaralda-Balboa');
insert into cities (name) values ('Atlántico-Baranoa');
insert into cities (name) values ('Huila-Baraya');
insert into cities (name) values ('Nariño-Barbacoas');
insert into cities (name) values ('Antioquia-Barbosa');
insert into cities (name) values ('Santander-Barbosa');
insert into cities (name) values ('Santander-Barichara');
insert into cities (name) values ('Meta-Barranca de Upí­a');
insert into cities (name) values ('Santander-Barrancabermeja');
insert into cities (name) values ('La Guajira-Barrancas');
insert into cities (name) values ('Bolí­var-Barranco de Loba');
insert into cities (name) values ('Atlántico-Barranquilla');
insert into cities (name) values ('Cesar-Becerrí­l');
insert into cities (name) values ('Caldas-Belalcázar');
insert into cities (name) values ('Antioquia-Bello');
insert into cities (name) values ('Antioquia-Belmira');
insert into cities (name) values ('Cundinamarca-Beltrán');
insert into cities (name) values ('Boyacá-Belén');
insert into cities (name) values ('Nariño-Belén');
insert into cities (name) values ('Chocó-Belén de Bajirá');
insert into cities (name) values ('Risaralda-Belén de Umbrí­a');
insert into cities (name) values ('Caquetá-Belén de los Andaquí­es');
insert into cities (name) values ('Boyacá-Berbeo');
insert into cities (name) values ('Antioquia-Betania');
insert into cities (name) values ('Boyacá-Beteitiva');
insert into cities (name) values ('Antioquia-Betulia');
insert into cities (name) values ('Santander-Betulia');
insert into cities (name) values ('Cundinamarca-Bituima');
insert into cities (name) values ('Boyacá-Boavita');
insert into cities (name) values ('Norte de Santander-Bochalema');
insert into cities (name) values ('Cundinamarca-Bogotá D.C.');
insert into cities (name) values ('Cundinamarca-Bojacá');
insert into cities (name) values ('Chocó-Bojayá (Bellavista)');
insert into cities (name) values ('Antioquia-Bolí­var');
insert into cities (name) values ('Cauca-Bolí­var');
insert into cities (name) values ('Santander-Bolí­var');
insert into cities (name) values ('Valle del Cauca-Bolí­var');
insert into cities (name) values ('Cesar-Bosconia');
insert into cities (name) values ('Boyacá-Boyacá');
insert into cities (name) values ('Antioquia-Briceño');
insert into cities (name) values ('Boyacá-Briceño');
insert into cities (name) values ('Santander-Bucaramanga');
insert into cities (name) values ('Norte de Santander-Bucarasica');
insert into cities (name) values ('Valle del Cauca-Buenaventura');
insert into cities (name) values ('Boyacá-Buenavista');
insert into cities (name) values ('Córdoba-Buenavista');
insert into cities (name) values ('Quindí­o-Buenavista');
insert into cities (name) values ('Sucre-Buenavista');
insert into cities (name) values ('Cauca-Buenos Aires');
insert into cities (name) values ('Nariño-Buesaco');
insert into cities (name) values ('Valle del Cauca-Buga');
insert into cities (name) values ('Valle del Cauca-Bugalagrande');
insert into cities (name) values ('Antioquia-Burí­tica');
insert into cities (name) values ('Boyacá-Busbanza');
insert into cities (name) values ('Cundinamarca-Cabrera');
insert into cities (name) values ('Santander-Cabrera');
insert into cities (name) values ('Meta-Cabuyaro');
insert into cities (name) values ('Cundinamarca-Cachipay');
insert into cities (name) values ('Antioquia-Caicedo');
insert into cities (name) values ('Valle del Cauca-Caicedonia');
insert into cities (name) values ('Sucre-Caimito');
insert into cities (name) values ('Tolima-Cajamarca');
insert into cities (name) values ('Cauca-Cajibí­o');
insert into cities (name) values ('Cundinamarca-Cajicá');
insert into cities (name) values ('Bolí­var-Calamar');
insert into cities (name) values ('Guaviare-Calamar');
insert into cities (name) values ('Quindí­o-Calarcá');
insert into cities (name) values ('Antioquia-Caldas');
insert into cities (name) values ('Boyacá-Caldas');
insert into cities (name) values ('Cauca-Caldono');
insert into cities (name) values ('Santander-California');
insert into cities (name) values ('Valle del Cauca-Calima (Darién)');
insert into cities (name) values ('Cauca-Caloto');
insert into cities (name) values ('Valle del Cauca-Calí­');
insert into cities (name) values ('Antioquia-Campamento');
insert into cities (name) values ('Atlántico-Campo de la Cruz');
insert into cities (name) values ('Huila-Campoalegre');
insert into cities (name) values ('Boyacá-Campohermoso');
insert into cities (name) values ('Córdoba-Canalete');
insert into cities (name) values ('Atlántico-Candelaria');
insert into cities (name) values ('Valle del Cauca-Candelaria');
insert into cities (name) values ('Bolí­var-Cantagallo');
insert into cities (name) values ('Chocó-Cantón de San Pablo');
insert into cities (name) values ('Cundinamarca-Caparrapí­');
insert into cities (name) values ('Santander-Capitanejo');
insert into cities (name) values ('Antioquia-Caracolí­');
insert into cities (name) values ('Antioquia-Caramanta');
insert into cities (name) values ('Santander-Carcasí­');
insert into cities (name) values ('Antioquia-Carepa');
insert into cities (name) values ('Tolima-Carmen de Apicalá');
insert into cities (name) values ('Cundinamarca-Carmen de Carupa');
insert into cities (name) values ('Antioquia-Carmen de Viboral');
insert into cities (name) values ('Chocó-Carmen del Darién (CURBARADí“)');
insert into cities (name) values ('Antioquia-Carolina');
insert into cities (name) values ('Bolí­var-Cartagena');
insert into cities (name) values ('Caquetá-Cartagena del Chairá');
insert into cities (name) values ('Valle del Cauca-Cartago');
insert into cities (name) values ('Vaupés-Caruríº');
insert into cities (name) values ('Tolima-Casabianca');
insert into cities (name) values ('Meta-Castilla la Nueva');
insert into cities (name) values ('Antioquia-Caucasia');
insert into cities (name) values ('Antioquia-Cañasgordas');
insert into cities (name) values ('Santander-Cepita');
insert into cities (name) values ('Córdoba-Cereté');
insert into cities (name) values ('Boyacá-Cerinza');
insert into cities (name) values ('Santander-Cerrito');
insert into cities (name) values ('Magdalena-Cerro San Antonio');
insert into cities (name) values ('Nariño-Chachaguí­');
insert into cities (name) values ('Cundinamarca-Chaguaní­');
insert into cities (name) values ('Sucre-Chalán');
insert into cities (name) values ('Tolima-Chaparral');
insert into cities (name) values ('Santander-Charalá');
insert into cities (name) values ('Santander-Charta');
insert into cities (name) values ('Antioquia-Chigorodó');
insert into cities (name) values ('Santander-Chima');
insert into cities (name) values ('Cesar-Chimichagua');
insert into cities (name) values ('Córdoba-Chimá');
insert into cities (name) values ('Boyacá-Chinavita');
insert into cities (name) values ('Caldas-Chinchiná');
insert into cities (name) values ('Norte de Santander-Chinácota');
insert into cities (name) values ('Córdoba-Chiníº');
insert into cities (name) values ('Cundinamarca-Chipaque');
insert into cities (name) values ('Santander-Chipatá');
insert into cities (name) values ('Boyacá-Chiquinquirá');
insert into cities (name) values ('Cesar-Chiriguaná');
insert into cities (name) values ('Boyacá-Chiscas');
insert into cities (name) values ('Boyacá-Chita');
insert into cities (name) values ('Norte de Santander-Chitagá');
insert into cities (name) values ('Boyacá-Chitaraque');
insert into cities (name) values ('Boyacá-Chivatá');
insert into cities (name) values ('Magdalena-Chivolo');
insert into cities (name) values ('Cundinamarca-Choachí­');
insert into cities (name) values ('Cundinamarca-Chocontá');
insert into cities (name) values ('Casanare-Chámeza');
insert into cities (name) values ('Cundinamarca-Chí­a');
insert into cities (name) values ('Boyacá-Chí­quiza');
insert into cities (name) values ('Boyacá-Chí­vor');
insert into cities (name) values ('Bolí­var-Cicuco');
insert into cities (name) values ('Santander-Cimitarra');
insert into cities (name) values ('Quindí­o-Circasia');
insert into cities (name) values ('Antioquia-Cisneros');
insert into cities (name) values ('Boyacá-Ciénaga');
insert into cities (name) values ('Magdalena-Ciénaga');
insert into cities (name) values ('Córdoba-Ciénaga de Oro');
insert into cities (name) values ('Bolí­var-Clemencia');
insert into cities (name) values ('Antioquia-Cocorná');
insert into cities (name) values ('Tolima-Coello');
insert into cities (name) values ('Cundinamarca-Cogua');
insert into cities (name) values ('Huila-Colombia');
insert into cities (name) values ('Sucre-Colosó (Ricaurte)');
insert into cities (name) values ('Putumayo-Colón');
insert into cities (name) values ('Nariño-Colón (Génova)');
insert into cities (name) values ('Antioquia-Concepción');
insert into cities (name) values ('Santander-Concepción');
insert into cities (name) values ('Antioquia-Concordia');
insert into cities (name) values ('Magdalena-Concordia');
insert into cities (name) values ('Chocó-Condoto');
insert into cities (name) values ('Santander-Confines');
insert into cities (name) values ('Nariño-Consaca');
insert into cities (name) values ('Nariño-Contadero');
insert into cities (name) values ('Santander-Contratación');
insert into cities (name) values ('Norte de Santander-Convención');
insert into cities (name) values ('Antioquia-Copacabana');
insert into cities (name) values ('Boyacá-Coper');
insert into cities (name) values ('Quindí­o-Cordobá');
insert into cities (name) values ('Cauca-Corinto');
insert into cities (name) values ('Santander-Coromoro');
insert into cities (name) values ('Sucre-Corozal');
insert into cities (name) values ('Boyacá-Corrales');
insert into cities (name) values ('Cundinamarca-Cota');
insert into cities (name) values ('Córdoba-Cotorra');
insert into cities (name) values ('Boyacá-Covarachí­a');
insert into cities (name) values ('Sucre-Coveñas');
insert into cities (name) values ('Tolima-Coyaima');
insert into cities (name) values ('Arauca-Cravo Norte');
insert into cities (name) values ('Nariño-Cuaspud (Carlosama)');
insert into cities (name) values ('Meta-Cubarral');
insert into cities (name) values ('Boyacá-Cubará');
insert into cities (name) values ('Boyacá-Cucaita');
insert into cities (name) values ('Cundinamarca-Cucunubá');
insert into cities (name) values ('Norte de Santander-Cucutilla');
insert into cities (name) values ('Boyacá-Cuitiva');
insert into cities (name) values ('Meta-Cumaral');
insert into cities (name) values ('Vichada-Cumaribo');
insert into cities (name) values ('Nariño-Cumbal');
insert into cities (name) values ('Nariño-Cumbitara');
insert into cities (name) values ('Tolima-Cunday');
insert into cities (name) values ('Caquetá-Curillo');
insert into cities (name) values ('Santander-Curití­');
insert into cities (name) values ('Cesar-Curumaní­');
insert into cities (name) values ('Antioquia-Cáceres');
insert into cities (name) values ('Norte de Santander-Cáchira');
insert into cities (name) values ('Norte de Santander-Cácota');
insert into cities (name) values ('Cundinamarca-Cáqueza');
insert into cities (name) values ('Chocó-Cértegui');
insert into cities (name) values ('Boyacá-Cómbita');
insert into cities (name) values ('Bolí­var-Córdoba');
insert into cities (name) values ('Nariño-Córdoba');
insert into cities (name) values ('Norte de Santander-Cíºcuta');
insert into cities (name) values ('Antioquia-Dabeiba');
insert into cities (name) values ('Valle del Cauca-Dagua');
insert into cities (name) values ('La Guajira-Dibulla');
insert into cities (name) values ('La Guajira-Distracción');
insert into cities (name) values ('Tolima-Dolores');
insert into cities (name) values ('Antioquia-Don Matí­as');
insert into cities (name) values ('Risaralda-Dos Quebradas');
insert into cities (name) values ('Boyacá-Duitama');
insert into cities (name) values ('Norte de Santander-Durania');
insert into cities (name) values ('Antioquia-Ebéjico');
insert into cities (name) values ('Antioquia-El Bagre');
insert into cities (name) values ('Magdalena-El Banco');
insert into cities (name) values ('Valle del Cauca-El Cairo');
insert into cities (name) values ('Meta-El Calvario');
insert into cities (name) values ('Norte de Santander-El Carmen');
insert into cities (name) values ('Santander-El Carmen');
insert into cities (name) values ('Chocó-El Carmen de Atrato');
insert into cities (name) values ('Bolí­var-El Carmen de Bolí­var');
insert into cities (name) values ('Meta-El Castillo');
insert into cities (name) values ('Valle del Cauca-El Cerrito');
insert into cities (name) values ('Nariño-El Charco');
insert into cities (name) values ('Boyacá-El Cocuy');
insert into cities (name) values ('Cundinamarca-El Colegio');
insert into cities (name) values ('Cesar-El Copey');
insert into cities (name) values ('Caquetá-El Doncello');
insert into cities (name) values ('Meta-El Dorado');
insert into cities (name) values ('Valle del Cauca-El Dovio');
insert into cities (name) values ('Boyacá-El Espino');
insert into cities (name) values ('Santander-El Guacamayo');
insert into cities (name) values ('Bolí­var-El Guamo');
insert into cities (name) values ('La Guajira-El Molino');
insert into cities (name) values ('Cesar-El Paso');
insert into cities (name) values ('Caquetá-El Paujil');
insert into cities (name) values ('Nariño-El Peñol');
insert into cities (name) values ('Bolí­var-El Peñon');
insert into cities (name) values ('Santander-El Peñon');
insert into cities (name) values ('Cundinamarca-El Peñón');
insert into cities (name) values ('Magdalena-El Piñon');
insert into cities (name) values ('Santander-El Playón');
insert into cities (name) values ('Guaviare-El Retorno');
insert into cities (name) values ('Magdalena-El Retén');
insert into cities (name) values ('Sucre-El Roble');
insert into cities (name) values ('Cundinamarca-El Rosal');
insert into cities (name) values ('Nariño-El Rosario');
insert into cities (name) values ('Nariño-El Tablón de Gómez');
insert into cities (name) values ('Cauca-El Tambo');
insert into cities (name) values ('Nariño-El Tambo');
insert into cities (name) values ('Norte de Santander-El Tarra');
insert into cities (name) values ('Norte de Santander-El Zulia');
insert into cities (name) values ('Valle del Cauca-El íguila');
insert into cities (name) values ('Huila-Elí­as');
insert into cities (name) values ('Santander-Encino');
insert into cities (name) values ('Santander-Enciso');
insert into cities (name) values ('Antioquia-Entrerrí­os');
insert into cities (name) values ('Antioquia-Envigado');
insert into cities (name) values ('Tolima-Espinal');
insert into cities (name) values ('Cundinamarca-Facatativá');
insert into cities (name) values ('Tolima-Falan');
insert into cities (name) values ('Caldas-Filadelfia');
insert into cities (name) values ('Quindí­o-Filandia');
insert into cities (name) values ('Boyacá-Firavitoba');
insert into cities (name) values ('Tolima-Flandes');
insert into cities (name) values ('Caquetá-Florencia');
insert into cities (name) values ('Cauca-Florencia');
insert into cities (name) values ('Boyacá-Floresta');
insert into cities (name) values ('Valle del Cauca-Florida');
insert into cities (name) values ('Santander-Floridablanca');
insert into cities (name) values ('Santander-Florián');
insert into cities (name) values ('La Guajira-Fonseca');
insert into cities (name) values ('Arauca-Fortíºl');
insert into cities (name) values ('Cundinamarca-Fosca');
insert into cities (name) values ('Nariño-Francisco Pizarro');
insert into cities (name) values ('Antioquia-Fredonia');
insert into cities (name) values ('Tolima-Fresno');
insert into cities (name) values ('Antioquia-Frontino');
insert into cities (name) values ('Meta-Fuente de Oro');
insert into cities (name) values ('Magdalena-Fundación');
insert into cities (name) values ('Nariño-Funes');
insert into cities (name) values ('Cundinamarca-Funza');
insert into cities (name) values ('Cundinamarca-Fusagasugá');
insert into cities (name) values ('Cundinamarca-Fómeque');
insert into cities (name) values ('Cundinamarca-Fíºquene');
insert into cities (name) values ('Cundinamarca-Gachalá');
insert into cities (name) values ('Cundinamarca-Gachancipá');
insert into cities (name) values ('Boyacá-Gachantivá');
insert into cities (name) values ('Cundinamarca-Gachetá');
insert into cities (name) values ('Atlántico-Galapa');
insert into cities (name) values ('Sucre-Galeras (Nueva Granada)');
insert into cities (name) values ('Santander-Galán');
insert into cities (name) values ('Cundinamarca-Gama');
insert into cities (name) values ('Cesar-Gamarra');
insert into cities (name) values ('Boyacá-Garagoa');
insert into cities (name) values ('Huila-Garzón');
insert into cities (name) values ('Huila-Gigante');
insert into cities (name) values ('Valle del Cauca-Ginebra');
insert into cities (name) values ('Antioquia-Giraldo');
insert into cities (name) values ('Cundinamarca-Girardot');
insert into cities (name) values ('Antioquia-Girardota');
insert into cities (name) values ('Santander-Girón');
insert into cities (name) values ('Cesar-Gonzalez');
insert into cities (name) values ('Norte de Santander-Gramalote');
insert into cities (name) values ('Antioquia-Granada');
insert into cities (name) values ('Cundinamarca-Granada');
insert into cities (name) values ('Meta-Granada');
insert into cities (name) values ('Santander-Guaca');
insert into cities (name) values ('Boyacá-Guacamayas');
insert into cities (name) values ('Valle del Cauca-Guacarí­');
insert into cities (name) values ('Nariño-Guachavés');
insert into cities (name) values ('Cauca-Guachené');
insert into cities (name) values ('Cundinamarca-Guachetá');
insert into cities (name) values ('Nariño-Guachucal');
insert into cities (name) values ('Antioquia-Guadalupe');
insert into cities (name) values ('Huila-Guadalupe');
insert into cities (name) values ('Santander-Guadalupe');
insert into cities (name) values ('Cundinamarca-Guaduas');
insert into cities (name) values ('Nariño-Guaitarilla');
insert into cities (name) values ('Nariño-Gualmatán');
insert into cities (name) values ('Magdalena-Guamal');
insert into cities (name) values ('Meta-Guamal');
insert into cities (name) values ('Tolima-Guamo');
insert into cities (name) values ('Santander-Guapota');
insert into cities (name) values ('Cauca-Guapí­');
insert into cities (name) values ('Sucre-Guaranda');
insert into cities (name) values ('Antioquia-Guarne');
insert into cities (name) values ('Cundinamarca-Guasca');
insert into cities (name) values ('Antioquia-Guatapé');
insert into cities (name) values ('Cundinamarca-Guataquí­');
insert into cities (name) values ('Cundinamarca-Guatavita');
insert into cities (name) values ('Boyacá-Guateque');
insert into cities (name) values ('Santander-Guavatá');
insert into cities (name) values ('Cundinamarca-Guayabal de Siquima');
insert into cities (name) values ('Cundinamarca-Guayabetal');
insert into cities (name) values ('Boyacá-Guayatá');
insert into cities (name) values ('Santander-Guepsa');
insert into cities (name) values ('Boyacá-Guicán');
insert into cities (name) values ('Cundinamarca-Gutiérrez');
insert into cities (name) values ('Risaralda-Guática');
insert into cities (name) values ('Santander-Gámbita');
insert into cities (name) values ('Boyacá-Gámeza');
insert into cities (name) values ('Quindí­o-Génova');
insert into cities (name) values ('Antioquia-Gómez Plata');
insert into cities (name) values ('Norte de Santander-Hacarí­');
insert into cities (name) values ('Bolí­var-Hatillo de Loba');
insert into cities (name) values ('Santander-Hato');
insert into cities (name) values ('Casanare-Hato Corozal');
insert into cities (name) values ('La Guajira-Hatonuevo');
insert into cities (name) values ('Antioquia-Heliconia');
insert into cities (name) values ('Norte de Santander-Herrán');
insert into cities (name) values ('Tolima-Herveo');
insert into cities (name) values ('Antioquia-Hispania');
insert into cities (name) values ('Huila-Hobo');
insert into cities (name) values ('Tolima-Honda');
insert into cities (name) values ('Tolima-Ibagué');
insert into cities (name) values ('Tolima-Icononzo');
insert into cities (name) values ('Nariño-Iles');
insert into cities (name) values ('Nariño-Imíºes');
insert into cities (name) values ('Cauca-Inzá');
insert into cities (name) values ('Guainí­a-Iní­rida');
insert into cities (name) values ('Nariño-Ipiales');
insert into cities (name) values ('Huila-Isnos');
insert into cities (name) values ('Chocó-Istmina');
insert into cities (name) values ('Antioquia-Itagí¼í­');
insert into cities (name) values ('Antioquia-Ituango');
insert into cities (name) values ('Boyacá-Izá');
insert into cities (name) values ('Cauca-Jambaló');
insert into cities (name) values ('Valle del Cauca-Jamundí­');
insert into cities (name) values ('Antioquia-Jardí­n');
insert into cities (name) values ('Boyacá-Jenesano');
insert into cities (name) values ('Antioquia-Jericó');
insert into cities (name) values ('Boyacá-Jericó');
insert into cities (name) values ('Cundinamarca-Jerusalén');
insert into cities (name) values ('Santander-Jesíºs Marí­a');
insert into cities (name) values ('Santander-Jordán');
insert into cities (name) values ('Atlántico-Juan de Acosta');
insert into cities (name) values ('Cundinamarca-Juní­n');
insert into cities (name) values ('Chocó-Juradó');
insert into cities (name) values ('Córdoba-La Apartada y La Frontera');
insert into cities (name) values ('Huila-La Argentina');
insert into cities (name) values ('Santander-La Belleza');
insert into cities (name) values ('Cundinamarca-La Calera');
insert into cities (name) values ('Boyacá-La Capilla');
insert into cities (name) values ('Antioquia-La Ceja');
insert into cities (name) values ('Risaralda-La Celia');
insert into cities (name) values ('Nariño-La Cruz');
insert into cities (name) values ('Valle del Cauca-La Cumbre');
insert into cities (name) values ('Caldas-La Dorada');
insert into cities (name) values ('Norte de Santander-La Esperanza');
insert into cities (name) values ('Antioquia-La Estrella');
insert into cities (name) values ('Nariño-La Florida');
insert into cities (name) values ('Cesar-La Gloria');
insert into cities (name) values ('Cesar-La Jagua de Ibirico');
insert into cities (name) values ('La Guajira-La Jagua del Pilar');
insert into cities (name) values ('Nariño-La Llanada');
insert into cities (name) values ('Meta-La Macarena');
insert into cities (name) values ('Caldas-La Merced');
insert into cities (name) values ('Cundinamarca-La Mesa');
insert into cities (name) values ('Caquetá-La Montañita');
insert into cities (name) values ('Cundinamarca-La Palma');
insert into cities (name) values ('Santander-La Paz');
insert into cities (name) values ('Cesar-La Paz (Robles)');
insert into cities (name) values ('Cundinamarca-La Peña');
insert into cities (name) values ('Antioquia-La Pintada');
insert into cities (name) values ('Huila-La Plata');
insert into cities (name) values ('Norte de Santander-La Playa');
insert into cities (name) values ('Vichada-La Primavera');
insert into cities (name) values ('Casanare-La Salina');
insert into cities (name) values ('Cauca-La Sierra');
insert into cities (name) values ('Quindí­o-La Tebaida');
insert into cities (name) values ('Nariño-La Tola');
insert into cities (name) values ('Antioquia-La Unión');
insert into cities (name) values ('Nariño-La Unión');
insert into cities (name) values ('Sucre-La Unión');
insert into cities (name) values ('Valle del Cauca-La Unión');
insert into cities (name) values ('Boyacá-La Uvita');
insert into cities (name) values ('Cauca-La Vega');
insert into cities (name) values ('Cundinamarca-La Vega');
insert into cities (name) values ('Boyacá-La Victoria');
insert into cities (name) values ('Caldas-La Victoria');
insert into cities (name) values ('Valle del Cauca-La Victoria');
insert into cities (name) values ('Risaralda-La Virginia');
insert into cities (name) values ('Norte de Santander-Labateca');
insert into cities (name) values ('Boyacá-Labranzagrande');
insert into cities (name) values ('Santander-Landázuri');
insert into cities (name) values ('Santander-Lebrija');
insert into cities (name) values ('Nariño-Leiva');
insert into cities (name) values ('Meta-Lejaní­as');
insert into cities (name) values ('Cundinamarca-Lenguazaque');
insert into cities (name) values ('Amazonas-Leticia');
insert into cities (name) values ('Antioquia-Liborina');
insert into cities (name) values ('Nariño-Linares');
insert into cities (name) values ('Chocó-Lloró');
insert into cities (name) values ('Córdoba-Lorica');
insert into cities (name) values ('Córdoba-Los Córdobas');
insert into cities (name) values ('Sucre-Los Palmitos');
insert into cities (name) values ('Norte de Santander-Los Patios');
insert into cities (name) values ('Santander-Los Santos');
insert into cities (name) values ('Norte de Santander-Lourdes');
insert into cities (name) values ('Atlántico-Luruaco');
insert into cities (name) values ('Tolima-Lérida');
insert into cities (name) values ('Tolima-Lí­bano');
insert into cities (name) values ('Cauca-López (Micay)');
insert into cities (name) values ('Boyacá-Macanal');
insert into cities (name) values ('Santander-Macaravita');
insert into cities (name) values ('Antioquia-Maceo');
insert into cities (name) values ('Cundinamarca-Machetá');
insert into cities (name) values ('Cundinamarca-Madrid');
insert into cities (name) values ('Bolí­var-Magangué');
insert into cities (name) values ('Nariño-Magí¼i (Payán)');
insert into cities (name) values ('Bolí­var-Mahates');
insert into cities (name) values ('La Guajira-Maicao');
insert into cities (name) values ('Sucre-Majagual');
insert into cities (name) values ('Atlántico-Malambo');
insert into cities (name) values ('Nariño-Mallama (Piedrancha)');
insert into cities (name) values ('Atlántico-Manatí­');
insert into cities (name) values ('La Guajira-Manaure');
insert into cities (name) values ('Cesar-Manaure Balcón del Cesar');
insert into cities (name) values ('Caldas-Manizales');
insert into cities (name) values ('Cundinamarca-Manta');
insert into cities (name) values ('Caldas-Manzanares');
insert into cities (name) values ('Casanare-Maní­');
insert into cities (name) values ('Meta-Mapiripan');
insert into cities (name) values ('Bolí­var-Margarita');
insert into cities (name) values ('Antioquia-Marinilla');
insert into cities (name) values ('Boyacá-Maripí­');
insert into cities (name) values ('Tolima-Mariquita');
insert into cities (name) values ('Caldas-Marmato');
insert into cities (name) values ('Caldas-Marquetalia');
insert into cities (name) values ('Risaralda-Marsella');
insert into cities (name) values ('Caldas-Marulanda');
insert into cities (name) values ('Bolí­var-Marí­a la Baja');
insert into cities (name) values ('Santander-Matanza');
insert into cities (name) values ('Antioquia-Medellí­n');
insert into cities (name) values ('Cundinamarca-Medina');
insert into cities (name) values ('Chocó-Medio Atrato');
insert into cities (name) values ('Chocó-Medio Baudó');
insert into cities (name) values ('Chocó-Medio San Juan (ANDAGOYA)');
insert into cities (name) values ('Tolima-Melgar');
insert into cities (name) values ('Cauca-Mercaderes');
insert into cities (name) values ('Meta-Mesetas');
insert into cities (name) values ('Caquetá-Milán');
insert into cities (name) values ('Boyacá-Miraflores');
insert into cities (name) values ('Guaviare-Miraflores');
insert into cities (name) values ('Cauca-Miranda');
insert into cities (name) values ('Risaralda-Mistrató');
insert into cities (name) values ('Vaupés-Mitíº');
insert into cities (name) values ('Putumayo-Mocoa');
insert into cities (name) values ('Santander-Mogotes');
insert into cities (name) values ('Santander-Molagavita');
insert into cities (name) values ('Córdoba-Momil');
insert into cities (name) values ('Bolí­var-Mompós');
insert into cities (name) values ('Boyacá-Mongua');
insert into cities (name) values ('Boyacá-Monguí­');
insert into cities (name) values ('Boyacá-Moniquirá');
insert into cities (name) values ('Antioquia-Montebello');
insert into cities (name) values ('Bolí­var-Montecristo');
insert into cities (name) values ('Córdoba-Montelí­bano');
insert into cities (name) values ('Quindí­o-Montenegro');
insert into cities (name) values ('Córdoba-Monteria');
insert into cities (name) values ('Casanare-Monterrey');
insert into cities (name) values ('Bolí­var-Morales');
insert into cities (name) values ('Cauca-Morales');
insert into cities (name) values ('Caquetá-Morelia');
insert into cities (name) values ('Sucre-Morroa');
insert into cities (name) values ('Cundinamarca-Mosquera');
insert into cities (name) values ('Nariño-Mosquera');
insert into cities (name) values ('Boyacá-Motavita');
insert into cities (name) values ('Córdoba-Moñitos');
insert into cities (name) values ('Tolima-Murillo');
insert into cities (name) values ('Antioquia-Murindó');
insert into cities (name) values ('Antioquia-Mutatá');
insert into cities (name) values ('Norte de Santander-Mutiscua');
insert into cities (name) values ('Boyacá-Muzo');
insert into cities (name) values ('Santander-Málaga');
insert into cities (name) values ('Antioquia-Nariño');
insert into cities (name) values ('Cundinamarca-Nariño');
insert into cities (name) values ('Nariño-Nariño');
insert into cities (name) values ('Tolima-Natagaima');
insert into cities (name) values ('Antioquia-Nechí­');
insert into cities (name) values ('Antioquia-Necoclí­');
insert into cities (name) values ('Caldas-Neira');
insert into cities (name) values ('Huila-Neiva');
insert into cities (name) values ('Cundinamarca-Nemocón');
insert into cities (name) values ('Cundinamarca-Nilo');
insert into cities (name) values ('Cundinamarca-Nimaima');
insert into cities (name) values ('Boyacá-Nobsa');
insert into cities (name) values ('Cundinamarca-Nocaima');
insert into cities (name) values ('Caldas-Norcasia');
insert into cities (name) values ('Bolí­var-Norosí­');
insert into cities (name) values ('Chocó-Novita');
insert into cities (name) values ('Magdalena-Nueva Granada');
insert into cities (name) values ('Boyacá-Nuevo Colón');
insert into cities (name) values ('Casanare-Nunchí­a');
insert into cities (name) values ('Chocó-Nuquí­');
insert into cities (name) values ('Huila-Nátaga');
insert into cities (name) values ('Valle del Cauca-Obando');
insert into cities (name) values ('Santander-Ocamonte');
insert into cities (name) values ('Norte de Santander-Ocaña');
insert into cities (name) values ('Santander-Oiba');
insert into cities (name) values ('Boyacá-Oicatá');
insert into cities (name) values ('Antioquia-Olaya');
insert into cities (name) values ('Nariño-Olaya Herrera');
insert into cities (name) values ('Santander-Onzaga');
insert into cities (name) values ('Huila-Oporapa');
insert into cities (name) values ('Putumayo-Orito');
insert into cities (name) values ('Casanare-Orocué');
insert into cities (name) values ('Tolima-Ortega');
insert into cities (name) values ('Nariño-Ospina');
insert into cities (name) values ('Boyacá-Otanche');
insert into cities (name) values ('Sucre-Ovejas');
insert into cities (name) values ('Boyacá-Pachavita');
insert into cities (name) values ('Cundinamarca-Pacho');
insert into cities (name) values ('Cauca-Padilla');
insert into cities (name) values ('Huila-Paicol');
insert into cities (name) values ('Cesar-Pailitas');
insert into cities (name) values ('Cundinamarca-Paime');
insert into cities (name) values ('Boyacá-Paipa');
insert into cities (name) values ('Boyacá-Pajarito');
insert into cities (name) values ('Huila-Palermo');
insert into cities (name) values ('Caldas-Palestina');
insert into cities (name) values ('Huila-Palestina');
insert into cities (name) values ('Santander-Palmar');
insert into cities (name) values ('Atlántico-Palmar de Varela');
insert into cities (name) values ('Santander-Palmas del Socorro');
insert into cities (name) values ('Valle del Cauca-Palmira');
insert into cities (name) values ('Sucre-Palmito');
insert into cities (name) values ('Tolima-Palocabildo');
insert into cities (name) values ('Norte de Santander-Pamplona');
insert into cities (name) values ('Norte de Santander-Pamplonita');
insert into cities (name) values ('Cundinamarca-Pandi');
insert into cities (name) values ('Boyacá-Panqueba');
insert into cities (name) values ('Cundinamarca-Paratebueno');
insert into cities (name) values ('Cundinamarca-Pasca');
insert into cities (name) values ('Cauca-Patí­a (El Bordo)');
insert into cities (name) values ('Boyacá-Pauna');
insert into cities (name) values ('Boyacá-Paya');
insert into cities (name) values ('Casanare-Paz de Ariporo');
insert into cities (name) values ('Boyacá-Paz de Rí­o');
insert into cities (name) values ('Magdalena-Pedraza');
insert into cities (name) values ('Cesar-Pelaya');
insert into cities (name) values ('Caldas-Pensilvania');
insert into cities (name) values ('Antioquia-Peque');
insert into cities (name) values ('Risaralda-Pereira');
insert into cities (name) values ('Boyacá-Pesca');
insert into cities (name) values ('Antioquia-Peñol');
insert into cities (name) values ('Cauca-Piamonte');
insert into cities (name) values ('Santander-Pie de Cuesta');
insert into cities (name) values ('Tolima-Piedras');
insert into cities (name) values ('Cauca-Piendamó');
insert into cities (name) values ('Quindí­o-Pijao');
insert into cities (name) values ('Magdalena-Pijiño');
insert into cities (name) values ('Santander-Pinchote');
insert into cities (name) values ('Bolí­var-Pinillos');
insert into cities (name) values ('Atlántico-Piojo');
insert into cities (name) values ('Boyacá-Pisva');
insert into cities (name) values ('Huila-Pital');
insert into cities (name) values ('Huila-Pitalito');
insert into cities (name) values ('Magdalena-Pivijay');
insert into cities (name) values ('Tolima-Planadas');
insert into cities (name) values ('Córdoba-Planeta Rica');
insert into cities (name) values ('Magdalena-Plato');
insert into cities (name) values ('Nariño-Policarpa');
insert into cities (name) values ('Atlántico-Polonuevo');
insert into cities (name) values ('Atlántico-Ponedera');
insert into cities (name) values ('Cauca-Popayán');
insert into cities (name) values ('Casanare-Pore');
insert into cities (name) values ('Nariño-Potosí­');
insert into cities (name) values ('Valle del Cauca-Pradera');
insert into cities (name) values ('Tolima-Prado');
insert into cities (name) values ('Nariño-Providencia');
insert into cities (name) values ('San Andrés-Providencia');
insert into cities (name) values ('Cesar-Pueblo Bello');
insert into cities (name) values ('Córdoba-Pueblo Nuevo');
insert into cities (name) values ('Risaralda-Pueblo Rico');
insert into cities (name) values ('Antioquia-Pueblorrico');
insert into cities (name) values ('Magdalena-Puebloviejo');
insert into cities (name) values ('Santander-Puente Nacional');
insert into cities (name) values ('Nariño-Puerres');
insert into cities (name) values ('Putumayo-Puerto Así­s');
insert into cities (name) values ('Antioquia-Puerto Berrí­o');
insert into cities (name) values ('Boyacá-Puerto Boyacá');
insert into cities (name) values ('Putumayo-Puerto Caicedo');
insert into cities (name) values ('Vichada-Puerto Carreño');
insert into cities (name) values ('Atlántico-Puerto Colombia');
insert into cities (name) values ('Meta-Puerto Concordia');
insert into cities (name) values ('Córdoba-Puerto Escondido');
insert into cities (name) values ('Meta-Puerto Gaitán');
insert into cities (name) values ('Putumayo-Puerto Guzmán');
insert into cities (name) values ('Putumayo-Puerto Leguí­zamo');
insert into cities (name) values ('Córdoba-Puerto Libertador');
insert into cities (name) values ('Meta-Puerto Lleras');
insert into cities (name) values ('Meta-Puerto López');
insert into cities (name) values ('Antioquia-Puerto Nare');
insert into cities (name) values ('Amazonas-Puerto Nariño');
insert into cities (name) values ('Santander-Puerto Parra');
insert into cities (name) values ('Caquetá-Puerto Rico');
insert into cities (name) values ('Meta-Puerto Rico');
insert into cities (name) values ('Arauca-Puerto Rondón');
insert into cities (name) values ('Cundinamarca-Puerto Salgar');
insert into cities (name) values ('Norte de Santander-Puerto Santander');
insert into cities (name) values ('Cauca-Puerto Tejada');
insert into cities (name) values ('Antioquia-Puerto Triunfo');
insert into cities (name) values ('Santander-Puerto Wilches');
insert into cities (name) values ('Cundinamarca-Pulí­');
insert into cities (name) values ('Nariño-Pupiales');
insert into cities (name) values ('Cauca-Puracé (Coconuco)');
insert into cities (name) values ('Tolima-Purificación');
insert into cities (name) values ('Córdoba-Purí­sima');
insert into cities (name) values ('Caldas-Pácora');
insert into cities (name) values ('Boyacá-Páez');
insert into cities (name) values ('Cauca-Páez (Belalcazar)');
insert into cities (name) values ('Santander-Páramo');
insert into cities (name) values ('Cundinamarca-Quebradanegra');
insert into cities (name) values ('Cundinamarca-Quetame');
insert into cities (name) values ('Chocó-Quibdó');
insert into cities (name) values ('Quindí­o-Quimbaya');
insert into cities (name) values ('Risaralda-Quinchí­a');
insert into cities (name) values ('Boyacá-Quipama');
insert into cities (name) values ('Cundinamarca-Quipile');
insert into cities (name) values ('Norte de Santander-Ragonvalia');
insert into cities (name) values ('Boyacá-Ramiriquí­');
insert into cities (name) values ('Casanare-Recetor');
insert into cities (name) values ('Bolí­var-Regidor');
insert into cities (name) values ('Antioquia-Remedios');
insert into cities (name) values ('Magdalena-Remolino');
insert into cities (name) values ('Atlántico-Repelón');
insert into cities (name) values ('Meta-Restrepo');
insert into cities (name) values ('Valle del Cauca-Restrepo');
insert into cities (name) values ('Antioquia-Retiro');
insert into cities (name) values ('Cundinamarca-Ricaurte');
insert into cities (name) values ('Nariño-Ricaurte');
insert into cities (name) values ('Santander-Rio Negro');
insert into cities (name) values ('Tolima-Rioblanco');
insert into cities (name) values ('Valle del Cauca-Riofrí­o');
insert into cities (name) values ('La Guajira-Riohacha');
insert into cities (name) values ('Caldas-Risaralda');
insert into cities (name) values ('Huila-Rivera');
insert into cities (name) values ('Nariño-Roberto Payán (San José)');
insert into cities (name) values ('Valle del Cauca-Roldanillo');
insert into cities (name) values ('Tolima-Roncesvalles');
insert into cities (name) values ('Boyacá-Rondón');
insert into cities (name) values ('Cauca-Rosas');
insert into cities (name) values ('Tolima-Rovira');
insert into cities (name) values ('Boyacá-Ráquira');
insert into cities (name) values ('Chocó-Rí­o Iró');
insert into cities (name) values ('Chocó-Rí­o Quito');
insert into cities (name) values ('Caldas-Rí­o Sucio');
insert into cities (name) values ('Bolí­var-Rí­o Viejo');
insert into cities (name) values ('Cesar-Rí­o de oro');
insert into cities (name) values ('Antioquia-Rí­onegro');
insert into cities (name) values ('Chocó-Rí­osucio');
insert into cities (name) values ('Santander-Sabana de Torres');
insert into cities (name) values ('Atlántico-Sabanagrande');
insert into cities (name) values ('Antioquia-Sabanalarga');
insert into cities (name) values ('Atlántico-Sabanalarga');
insert into cities (name) values ('Casanare-Sabanalarga');
insert into cities (name) values ('Magdalena-Sabanas de San Angel (SAN ANGEL)');
insert into cities (name) values ('Antioquia-Sabaneta');
insert into cities (name) values ('Boyacá-Saboyá');
insert into cities (name) values ('Córdoba-Sahagíºn');
insert into cities (name) values ('Huila-Saladoblanco');
insert into cities (name) values ('Caldas-Salamina');
insert into cities (name) values ('Magdalena-Salamina');
insert into cities (name) values ('Norte de Santander-Salazar');
insert into cities (name) values ('Tolima-Saldaña');
insert into cities (name) values ('Quindí­o-Salento');
insert into cities (name) values ('Antioquia-Salgar');
insert into cities (name) values ('Boyacá-Samacá');
insert into cities (name) values ('Nariño-Samaniego');
insert into cities (name) values ('Caldas-Samaná');
insert into cities (name) values ('Sucre-Sampués');
insert into cities (name) values ('Huila-San Agustí­n');
insert into cities (name) values ('Cesar-San Alberto');
insert into cities (name) values ('Santander-San Andrés');
insert into cities (name) values ('Córdoba-San Andrés Sotavento');
insert into cities (name) values ('Antioquia-San Andrés de Cuerquí­a');
insert into cities (name) values ('Córdoba-San Antero');
insert into cities (name) values ('Tolima-San Antonio');
insert into cities (name) values ('Cundinamarca-San Antonio de Tequendama');
insert into cities (name) values ('Santander-San Benito');
insert into cities (name) values ('Sucre-San Benito Abad');
insert into cities (name) values ('Cundinamarca-San Bernardo');
insert into cities (name) values ('Nariño-San Bernardo');
insert into cities (name) values ('Córdoba-San Bernardo del Viento');
insert into cities (name) values ('Norte de Santander-San Calixto');
insert into cities (name) values ('Antioquia-San Carlos');
insert into cities (name) values ('Córdoba-San Carlos');
insert into cities (name) values ('Meta-San Carlos de Guaroa');
insert into cities (name) values ('Cundinamarca-San Cayetano');
insert into cities (name) values ('Norte de Santander-San Cayetano');
insert into cities (name) values ('Bolí­var-San Cristobal');
insert into cities (name) values ('Cesar-San Diego');
insert into cities (name) values ('Boyacá-San Eduardo');
insert into cities (name) values ('Bolí­var-San Estanislao');
insert into cities (name) values ('Bolí­var-San Fernando');
insert into cities (name) values ('Antioquia-San Francisco');
insert into cities (name) values ('Cundinamarca-San Francisco');
insert into cities (name) values ('Putumayo-San Francisco');
insert into cities (name) values ('Santander-San Gí­l');
insert into cities (name) values ('Bolí­var-San Jacinto');
insert into cities (name) values ('Bolí­var-San Jacinto del Cauca');
insert into cities (name) values ('Antioquia-San Jerónimo');
insert into cities (name) values ('Santander-San Joaquí­n');
insert into cities (name) values ('Caldas-San José');
insert into cities (name) values ('Santander-San José de Miranda');
insert into cities (name) values ('Antioquia-San José de Montaña');
insert into cities (name) values ('Boyacá-San José de Pare');
insert into cities (name) values ('Córdoba-San José de Uré');
insert into cities (name) values ('Caquetá-San José del Fragua');
insert into cities (name) values ('Guaviare-San José del Guaviare');
insert into cities (name) values ('Chocó-San José del Palmar');
insert into cities (name) values ('Meta-San Juan de Arama');
insert into cities (name) values ('Sucre-San Juan de Betulia');
insert into cities (name) values ('Bolí­var-San Juan de Nepomuceno');
insert into cities (name) values ('Nariño-San Juan de Pasto');
insert into cities (name) values ('Cundinamarca-San Juan de Rí­o Seco');
insert into cities (name) values ('Antioquia-San Juan de Urabá');
insert into cities (name) values ('La Guajira-San Juan del Cesar');
insert into cities (name) values ('Meta-San Juanito');
insert into cities (name) values ('Nariño-San Lorenzo');
insert into cities (name) values ('Tolima-San Luis');
insert into cities (name) values ('Antioquia-San Luí­s');
insert into cities (name) values ('Boyacá-San Luí­s de Gaceno');
insert into cities (name) values ('Casanare-San Luí­s de Palenque');
insert into cities (name) values ('Sucre-San Marcos');
insert into cities (name) values ('Cesar-San Martí­n');
insert into cities (name) values ('Meta-San Martí­n');
insert into cities (name) values ('Bolí­var-San Martí­n de Loba');
insert into cities (name) values ('Boyacá-San Mateo');
insert into cities (name) values ('Santander-San Miguel');
insert into cities (name) values ('Putumayo-San Miguel');
insert into cities (name) values ('Boyacá-San Miguel de Sema');
insert into cities (name) values ('Sucre-San Onofre');
insert into cities (name) values ('Bolí­var-San Pablo');
insert into cities (name) values ('Nariño-San Pablo');
insert into cities (name) values ('Boyacá-San Pablo de Borbur');
insert into cities (name) values ('Antioquia-San Pedro');
insert into cities (name) values ('Sucre-San Pedro');
insert into cities (name) values ('Valle del Cauca-San Pedro');
insert into cities (name) values ('Nariño-San Pedro de Cartago');
insert into cities (name) values ('Antioquia-San Pedro de Urabá');
insert into cities (name) values ('Córdoba-San Pelayo');
insert into cities (name) values ('Antioquia-San Rafael');
insert into cities (name) values ('Antioquia-San Roque');
insert into cities (name) values ('Cauca-San Sebastián');
insert into cities (name) values ('Magdalena-San Sebastián de Buenavista');
insert into cities (name) values ('Antioquia-San Vicente');
insert into cities (name) values ('Caquetá-San Vicente del Caguán');
insert into cities (name) values ('Santander-San Vicente del Chucurí­');
insert into cities (name) values ('Magdalena-San Zenón');
insert into cities (name) values ('Nariño-Sandoná');
insert into cities (name) values ('Magdalena-Santa Ana');
insert into cities (name) values ('Antioquia-Santa Bárbara');
insert into cities (name) values ('Santander-Santa Bárbara');
insert into cities (name) values ('Nariño-Santa Bárbara (Iscuandé)');
insert into cities (name) values ('Magdalena-Santa Bárbara de Pinto');
insert into cities (name) values ('Bolí­var-Santa Catalina');
insert into cities (name) values ('Antioquia-Santa Fé de Antioquia');
insert into cities (name) values ('Chocó-Santa Genoveva de Docorodó');
insert into cities (name) values ('Santander-Santa Helena del Opón');
insert into cities (name) values ('Tolima-Santa Isabel');
insert into cities (name) values ('Atlántico-Santa Lucí­a');
insert into cities (name) values ('Magdalena-Santa Marta');
insert into cities (name) values ('Boyacá-Santa Marí­a');
insert into cities (name) values ('Huila-Santa Marí­a');
insert into cities (name) values ('Bolí­var-Santa Rosa');
insert into cities (name) values ('Cauca-Santa Rosa');
insert into cities (name) values ('Risaralda-Santa Rosa de Cabal');
insert into cities (name) values ('Antioquia-Santa Rosa de Osos');
insert into cities (name) values ('Boyacá-Santa Rosa de Viterbo');
insert into cities (name) values ('Bolí­var-Santa Rosa del Sur');
insert into cities (name) values ('Vichada-Santa Rosalí­a');
insert into cities (name) values ('Boyacá-Santa Sofí­a');
insert into cities (name) values ('Boyacá-Santana');
insert into cities (name) values ('Cauca-Santander de Quilichao');
insert into cities (name) values ('Norte de Santander-Santiago');
insert into cities (name) values ('Putumayo-Santiago');
insert into cities (name) values ('Antioquia-Santo Domingo');
insert into cities (name) values ('Atlántico-Santo Tomás');
insert into cities (name) values ('Antioquia-Santuario');
insert into cities (name) values ('Risaralda-Santuario');
insert into cities (name) values ('Nariño-Sapuyes');
insert into cities (name) values ('Arauca-Saravena');
insert into cities (name) values ('Norte de Santander-Sardinata');
insert into cities (name) values ('Cundinamarca-Sasaima');
insert into cities (name) values ('Boyacá-Sativanorte');
insert into cities (name) values ('Boyacá-Sativasur');
insert into cities (name) values ('Antioquia-Segovia');
insert into cities (name) values ('Cundinamarca-Sesquilé');
insert into cities (name) values ('Valle del Cauca-Sevilla');
insert into cities (name) values ('Boyacá-Siachoque');
insert into cities (name) values ('Cundinamarca-Sibaté');
insert into cities (name) values ('Putumayo-Sibundoy');
insert into cities (name) values ('Norte de Santander-Silos');
insert into cities (name) values ('Cundinamarca-Silvania');
insert into cities (name) values ('Cauca-Silvia');
insert into cities (name) values ('Santander-Simacota');
insert into cities (name) values ('Cundinamarca-Simijaca');
insert into cities (name) values ('Bolí­var-Simití­');
insert into cities (name) values ('Sucre-Sincelejo');
insert into cities (name) values ('Sucre-Sincé');
insert into cities (name) values ('Chocó-Sipí­');
insert into cities (name) values ('Magdalena-Sitionuevo');
insert into cities (name) values ('Cundinamarca-Soacha');
insert into cities (name) values ('Boyacá-Soatá');
insert into cities (name) values ('Boyacá-Socha');
insert into cities (name) values ('Santander-Socorro');
insert into cities (name) values ('Boyacá-Socotá');
insert into cities (name) values ('Boyacá-Sogamoso');
insert into cities (name) values ('Caquetá-Solano');
insert into cities (name) values ('Atlántico-Soledad');
insert into cities (name) values ('Caquetá-Solita');
insert into cities (name) values ('Boyacá-Somondoco');
insert into cities (name) values ('Antioquia-Sonsón');
insert into cities (name) values ('Antioquia-Sopetrán');
insert into cities (name) values ('Bolí­var-Soplaviento');
insert into cities (name) values ('Cundinamarca-Sopó');
insert into cities (name) values ('Boyacá-Sora');
insert into cities (name) values ('Boyacá-Soracá');
insert into cities (name) values ('Boyacá-Sotaquirá');
insert into cities (name) values ('Cauca-Sotara (Paispamba)');
insert into cities (name) values ('Nariño-Sotomayor (Los Andes)');
insert into cities (name) values ('Santander-Suaita');
insert into cities (name) values ('Atlántico-Suan');
insert into cities (name) values ('Huila-Suaza');
insert into cities (name) values ('Cundinamarca-Subachoque');
insert into cities (name) values ('Cauca-Sucre');
insert into cities (name) values ('Santander-Sucre');
insert into cities (name) values ('Sucre-Sucre');
insert into cities (name) values ('Cundinamarca-Suesca');
insert into cities (name) values ('Cundinamarca-Supatá');
insert into cities (name) values ('Caldas-Supí­a');
insert into cities (name) values ('Santander-Suratá');
insert into cities (name) values ('Cundinamarca-Susa');
insert into cities (name) values ('Boyacá-Susacón');
insert into cities (name) values ('Boyacá-Sutamarchán');
insert into cities (name) values ('Cundinamarca-Sutatausa');
insert into cities (name) values ('Boyacá-Sutatenza');
insert into cities (name) values ('Cauca-Suárez');
insert into cities (name) values ('Tolima-Suárez');
insert into cities (name) values ('Casanare-Sácama');
insert into cities (name) values ('Boyacá-Sáchica');
insert into cities (name) values ('Cundinamarca-Tabio');
insert into cities (name) values ('Chocó-Tadó');
insert into cities (name) values ('Bolí­var-Talaigua Nuevo');
insert into cities (name) values ('Cesar-Tamalameque');
insert into cities (name) values ('Arauca-Tame');
insert into cities (name) values ('Nariño-Taminango');
insert into cities (name) values ('Nariño-Tangua');
insert into cities (name) values ('Vaupés-Taraira');
insert into cities (name) values ('Antioquia-Tarazá');
insert into cities (name) values ('Huila-Tarqui');
insert into cities (name) values ('Antioquia-Tarso');
insert into cities (name) values ('Boyacá-Tasco');
insert into cities (name) values ('Casanare-Tauramena');
insert into cities (name) values ('Cundinamarca-Tausa');
insert into cities (name) values ('Huila-Tello');
insert into cities (name) values ('Cundinamarca-Tena');
insert into cities (name) values ('Magdalena-Tenerife');
insert into cities (name) values ('Cundinamarca-Tenjo');
insert into cities (name) values ('Boyacá-Tenza');
insert into cities (name) values ('Norte de Santander-Teorama');
insert into cities (name) values ('Huila-Teruel');
insert into cities (name) values ('Huila-Tesalia');
insert into cities (name) values ('Cundinamarca-Tibacuy');
insert into cities (name) values ('Boyacá-Tibaná');
insert into cities (name) values ('Boyacá-Tibasosa');
insert into cities (name) values ('Cundinamarca-Tibirita');
insert into cities (name) values ('Norte de Santander-Tibíº');
insert into cities (name) values ('Córdoba-Tierralta');
insert into cities (name) values ('Huila-Timaná');
insert into cities (name) values ('Cauca-Timbiquí­');
insert into cities (name) values ('Cauca-Timbí­o');
insert into cities (name) values ('Boyacá-Tinjacá');
insert into cities (name) values ('Boyacá-Tipacoque');
insert into cities (name) values ('Bolí­var-Tiquisio (Puerto Rico)');
insert into cities (name) values ('Antioquia-Titiribí­');
insert into cities (name) values ('Boyacá-Toca');
insert into cities (name) values ('Cundinamarca-Tocaima');
insert into cities (name) values ('Cundinamarca-Tocancipá');
insert into cities (name) values ('Boyacá-Toguí­');
insert into cities (name) values ('Antioquia-Toledo');
insert into cities (name) values ('Norte de Santander-Toledo');
insert into cities (name) values ('Sucre-Tolíº');
insert into cities (name) values ('Sucre-Tolíº Viejo');
insert into cities (name) values ('Santander-Tona');
insert into cities (name) values ('Boyacá-Topagá');
insert into cities (name) values ('Cundinamarca-Topaipí­');
insert into cities (name) values ('Cauca-Toribí­o');
insert into cities (name) values ('Valle del Cauca-Toro');
insert into cities (name) values ('Boyacá-Tota');
insert into cities (name) values ('Cauca-Totoró');
insert into cities (name) values ('Casanare-Trinidad');
insert into cities (name) values ('Valle del Cauca-Trujillo');
insert into cities (name) values ('Atlántico-Tubará');
insert into cities (name) values ('Córdoba-Tuchí­n');
insert into cities (name) values ('Valle del Cauca-Tulíºa');
insert into cities (name) values ('Nariño-Tumaco');
insert into cities (name) values ('Boyacá-Tunja');
insert into cities (name) values ('Boyacá-Tunungua');
insert into cities (name) values ('Bolí­var-Turbaco');
insert into cities (name) values ('Bolí­var-Turbaná');
insert into cities (name) values ('Antioquia-Turbo');
insert into cities (name) values ('Boyacá-Turmequé');
insert into cities (name) values ('Boyacá-Tuta');
insert into cities (name) values ('Boyacá-Tutasá');
insert into cities (name) values ('Casanare-Támara');
insert into cities (name) values ('Antioquia-Támesis');
insert into cities (name) values ('Nariño-Tíºquerres');
insert into cities (name) values ('Cundinamarca-Ubalá');
insert into cities (name) values ('Cundinamarca-Ubaque');
insert into cities (name) values ('Cundinamarca-Ubaté');
insert into cities (name) values ('Valle del Cauca-Ulloa');
insert into cities (name) values ('Cundinamarca-Une');
insert into cities (name) values ('Chocó-Unguí­a');
insert into cities (name) values ('Chocó-Unión Panamericana (íNIMAS)');
insert into cities (name) values ('Antioquia-Uramita');
insert into cities (name) values ('Meta-Uribe');
insert into cities (name) values ('La Guajira-Uribia');
insert into cities (name) values ('Antioquia-Urrao');
insert into cities (name) values ('La Guajira-Urumita');
insert into cities (name) values ('Atlántico-Usiacuri');
insert into cities (name) values ('Antioquia-Valdivia');
insert into cities (name) values ('Córdoba-Valencia');
insert into cities (name) values ('Santander-Valle de San José');
insert into cities (name) values ('Tolima-Valle de San Juan');
insert into cities (name) values ('Putumayo-Valle del Guamuez');
insert into cities (name) values ('Cesar-Valledupar');
insert into cities (name) values ('Antioquia-Valparaiso');
insert into cities (name) values ('Caquetá-Valparaiso');
insert into cities (name) values ('Antioquia-Vegachí­');
insert into cities (name) values ('Tolima-Venadillo');
insert into cities (name) values ('Antioquia-Venecia');
insert into cities (name) values ('Cundinamarca-Venecia (Ospina Pérez)');
insert into cities (name) values ('Boyacá-Ventaquemada');
insert into cities (name) values ('Cundinamarca-Vergara');
insert into cities (name) values ('Valle del Cauca-Versalles');
insert into cities (name) values ('Santander-Vetas');
insert into cities (name) values ('Cundinamarca-Viani');
insert into cities (name) values ('Antioquia-Vigí­a del Fuerte');
insert into cities (name) values ('Valle del Cauca-Vijes');
insert into cities (name) values ('Norte de Santander-Villa Caro');
insert into cities (name) values ('Cauca-Villa Rica');
insert into cities (name) values ('Boyacá-Villa de Leiva');
insert into cities (name) values ('Norte de Santander-Villa del Rosario');
insert into cities (name) values ('Putumayo-Villagarzón');
insert into cities (name) values ('Cundinamarca-Villagómez');
insert into cities (name) values ('Tolima-Villahermosa');
insert into cities (name) values ('Caldas-Villamarí­a');
insert into cities (name) values ('Bolí­var-Villanueva');
insert into cities (name) values ('La Guajira-Villanueva');
insert into cities (name) values ('Santander-Villanueva');
insert into cities (name) values ('Casanare-Villanueva');
insert into cities (name) values ('Cundinamarca-Villapinzón');
insert into cities (name) values ('Tolima-Villarrica');
insert into cities (name) values ('Meta-Villavicencio');
insert into cities (name) values ('Huila-Villavieja');
insert into cities (name) values ('Cundinamarca-Villeta');
insert into cities (name) values ('Cundinamarca-Viotá');
insert into cities (name) values ('Boyacá-Viracachá');
insert into cities (name) values ('Meta-Vista Hermosa');
insert into cities (name) values ('Caldas-Viterbo');
insert into cities (name) values ('Santander-Vélez');
insert into cities (name) values ('Cundinamarca-Yacopí­');
insert into cities (name) values ('Nariño-Yacuanquer');
insert into cities (name) values ('Huila-Yaguará');
insert into cities (name) values ('Antioquia-Yalí­');
insert into cities (name) values ('Antioquia-Yarumal');
insert into cities (name) values ('Antioquia-Yolombó');
insert into cities (name) values ('Antioquia-Yondó (Casabe)');
insert into cities (name) values ('Casanare-Yopal');
insert into cities (name) values ('Valle del Cauca-Yotoco');
insert into cities (name) values ('Valle del Cauca-Yumbo');
insert into cities (name) values ('Bolí­var-Zambrano');
insert into cities (name) values ('Santander-Zapatoca');
insert into cities (name) values ('Magdalena-Zapayán (PUNTA DE PIEDRAS)');
insert into cities (name) values ('Antioquia-Zaragoza');
insert into cities (name) values ('Valle del Cauca-Zarzal');
insert into cities (name) values ('Boyacá-Zetaquirá');
insert into cities (name) values ('Cundinamarca-Zipacón');
insert into cities (name) values ('Cundinamarca-Zipaquirá');
insert into cities (name) values ('Magdalena-Zona Bananera (PRADO - SEVILLA)');
insert into cities (name) values ('Norte de Santander-íbrego');
insert into cities (name) values ('Huila-íquira');
insert into cities (name) values ('Boyacá-úmbita');
insert into cities (name) values ('Cundinamarca-útica');
